#!/bin/bash
# Tests for hooks/landing-gate.sh — THE LANDING SWEEP (epic-16 wave-03, slice T4c/T4d).
#
# Stop. The gate used to run on SubagentStop and judge the ONE agent that stopped. That
# event is structurally invisible to a skill-frontmatter registration (T4b §3: skill hooks
# live in `appState.sessionHooks` keyed by SESSION id, and every subagent-context event is
# dispatched under the SUBAGENT's id, which has no entry there), so the wall was inert the
# moment registration moved into SKILL.md. It now runs on `Stop`, which IS delivered to the
# skill channel, fires once per orchestrator turn, and — the fact that makes the latency a
# non-issue — is GENERATED BY a background agent's landing, which wakes a fresh turn that
# closes 2.5–3.7 s later (T4b §2.3, §4).
#
# The shape that replaces "judge the stopping agent" is a SWEEP: every roster row whose
# `agent_id` is absent from the payload's `background_tasks[]` has landed, and each one is
# verdicted exactly once, ever.
#
# Governing evidence: .bionic/docs/record/session-20260814-wave-detector-terminal-state/
# t4b-probe-report.md §6 (the ratified mechanism), §2–§4 (its evidence).
#
# HERMETIC. Every payload is crafted and piped straight into the gate; nothing here stops a
# real subagent, touches the live installed hooks, or depends on a live wave. Repos are
# throwaway `git init`s under a mktemp'd sandbox, and the roster/plan fixtures are written
# as files.
#
# THE SWEEPER IS REAL IN EVERY CASE THAT HAS ONE. The gate consumes
# `session-sweeper.sh verdict <name>` and never re-implements its predicate, so a stubbed
# verdict would leave exactly the seam this slice exists to close (rule: seam-blindness —
# a seam substituting the value-under-test leaves the production path unverified). The gate
# resolves the sweeper as its own SIBLING, which is what bootstrap's `hooks/*.sh` install
# produces, so Section 6 gets its absent/erroring sweeper by running a COPY of the gate out
# of a directory holding a different sibling — no env override, no PATH seam.
#
# Usage: bash tests/landing-gate.test.sh

set -uo pipefail

. "$(dirname "$0")/lib/resolve-roots.sh"
. "$(dirname "$0")/lib/assert.sh"
. "$(dirname "$0")/lib/roster-row.sh"
. "$(dirname "$0")/lib/swept-marker.sh"

HOOKS_DIR="${BIONIC_HOOKS_DIR}"
GATE="$HOOKS_DIR/landing-gate.sh"

SANDBOX="$(cd "$(mktemp -d "${TMPDIR:-/tmp}/landing-gate-test.XXXXXX")" && pwd)"
BG_PIDS=""
cleanup() {
  local p
  for p in $BG_PIDS; do kill -9 "$p" 2>/dev/null; done
  chmod -R u+rwX "$SANDBOX" 2>/dev/null
  rm -rf "$SANDBOX"
}
trap cleanup EXIT

# expect_status, expect_contains, expect_absent, expect_empty, expect_eq are
# the framework's (tests/lib/assert.sh) — identical semantics to the private
# definitions this suite carried (grep -qF vs the framework's case glob agree
# on every needle here: all single-line, per the framework's own docblock).
# expect_gt/expect_lt are not owned names (A-17 W+1) and stay local, built on
# the framework's ok/no. This suite's own section() was a plain banner
# printer with the framework's exact signature (A-10c) — deleted outright,
# every existing `section "..."` call site binds unchanged, now WITH the
# section-floor enforcement it never had before.
expect_gt() { if [ "$2" -gt "$3" ] 2>/dev/null; then ok "$1"; else no "$1" "expected > $3, got $2"; fi; }
expect_lt() { if [ "$2" -lt "$3" ] 2>/dev/null; then ok "$1"; else no "$1" "expected < $3, got $2"; fi; }

# ---------- fixtures ----------
#
# FIXTURE FIDELITY (declared per rule fixtures-can-pin-away-the-test).
#
#   * Stop payload ENVELOPE — VERBATIM key set from t4b-probe-report.md §2.1, a live Stop
#     captured 2026-08-15 (CLI 2.1.233): background_tasks, cwd, effort, hook_event_name,
#     last_assistant_message, permission_mode, prompt_id, session_crons, session_id,
#     stop_hook_active, transcript_path. The `background_tasks[]` row shape is §2.2's
#     verbatim: {id, type, status, description, agent_type}.
#   * agent ids — the transcript form the platform mints for an Agent dispatch
#     (`a8e3d9b517abc6bf7`, §4), which is the SAME string `tool_response.agentId` returns and
#     the SAME string `background_tasks[].id` carries. That triple identity is the join this
#     slice is built on, so the fixtures spell one form and never three.
#   * roster rows — the roster-state/v1 field set and ORDER written by
#     hooks/dispatch-preflight.sh (the `ROW=` assignment), copied from
#     tests/session-sweeper.test.sh's `mkrow`. This suite's subject reads the roster for the
#     JOIN KEY only; the contract is read by the sweeper, which is the real one here.
#   * SYNTHESIZED and declared: session ids, plan text, deliverable paths, the marker process
#     a STILL-LIVE row claims. None is a platform surface.

SID="3b51bef0-d7bd-447a-bc65-8916c4b25353"
SID_B="7c2d1a04-55e8-4f31-9a70-1b8c3d0e6f22"

AID_A="a8e3d9b517abc6bf7"
AID_B="ab9751b8c5191a4e5"

# The live half of a Stop payload: one `background_tasks` row per id still running.
bg_tasks() {  # <agent-id>...
  local first=1 id
  printf '['
  for id in "$@"; do
    [ -n "$id" ] || continue
    [ "$first" -eq 1 ] || printf ','
    first=0
    printf '{"id":"%s","type":"subagent","status":"running","description":"a live dispatch","agent_type":"general-purpose"}' "$id"
  done
  printf ']'
}

# THE TEAMMATE'S OWN LIVE ROW. A named teammate is entered in `background_tasks[]` under a
# THIRD id namespace — an opaque nine-character token that appears in no other payload the
# session ever sees — and it NEVER LEAVES that array: measured `status:"running"` on the last
# Stop of the session, 2 m 41 s after the teammate had delivered its own SubagentStop
# (t1-probe-report.md §2.1, §2.3, CLI 2.1.233). Landing-by-disappearance is a subagent-only
# signal, so this row is what the SubagentStop arm must be indifferent to.
bg_teammate() {  # <opaque-id>
  printf '{"id":"%s","type":"teammate","status":"running","description":"a named teammate, still addressable..."}' "$1"
}

stop_payload() {  # <cwd> <session_id> <stop_hook_active> [live-agent-id...]
  local cwd="$1" sid="$2" active="$3"; shift 3
  cat <<JSON
{
  "session_id": "$sid",
  "transcript_path": "/tmp/transcripts/$sid.jsonl",
  "cwd": "$cwd",
  "prompt_id": "e30e6fb0-3868-467c-b092-ca03e55b4cd5",
  "permission_mode": "bypassPermissions",
  "effort": { "level": "high" },
  "hook_event_name": "Stop",
  "stop_hook_active": $active,
  "last_assistant_message": "The background probe agent completed and returned PONG.",
  "background_tasks": $(bg_tasks "$@"),
  "session_crons": []
}
JSON
}

# THE LANDING EVENT FOR A TEAMMATE (session-20260815-landing-supervision, T2). The key set is
# t1-probe-report.md §2.1's verbatim SubagentStop capture: agent_id (the TRANSCRIPT form),
# agent_type (which carries the dispatch NAME for a teammate and the subagent TYPE for an
# async dispatch — both readings are right, for different dispatch modes), agent_transcript_path,
# last_assistant_message, stop_hook_active, and the whole `background_tasks[]` array the Stop
# payload carries. This event reaches the gate through the SETTINGS channel behind
# hooks/agent-context-guard.sh; the skill channel never receives it (t1 §3).
substop_payload() {  # <cwd> <session_id> <agent_id> <agent_type> <stop_hook_active> [live-bg-json]
  local cwd="$1" sid="$2" aid="$3" atype="$4" active="$5" bg="${6:-[]}"
  cat <<JSON
{
  "session_id": "$sid",
  "transcript_path": "/tmp/transcripts/$sid.jsonl",
  "agent_transcript_path": "/tmp/transcripts/$sid/subagents/agent-$aid.jsonl",
  "cwd": "$cwd",
  "prompt_id": "e30e6fb0-3868-467c-b092-ca03e55b4cd5",
  "permission_mode": "bypassPermissions",
  "effort": { "level": "high" },
  "agent_id": "$aid",
  "agent_type": "$atype",
  "hook_event_name": "SubagentStop",
  "stop_hook_active": $active,
  "last_assistant_message": "Both steps completed.",
  "background_tasks": $bg,
  "session_crons": []
}
JSON
}

iso_ago() {  # <seconds ago> -> UTC ISO-8601, the launched_at shape
  date -u -v-"$1"S +%Y-%m-%dT%H:%M:%SZ 2>/dev/null \
    || date -u -d "-$1 seconds" +%Y-%m-%dT%H:%M:%SZ
}

# roster-state/v1, field set and order per hooks/dispatch-preflight.sh's writer.
mkrow() {  # <key=value>...
  local status=confirmed session="$SID" name=agent agent_id="$AID_A" launched_at=""
  local subagent_type=implementor model=opus deliverable="" duration="" progress=""
  local claims="" cadence="" waiver="" tool_use_id=toolu_x source=declared teammate_id="" kv
  local files="" has_files=0
  for kv in "$@"; do
    case "$kv" in
      source=*)      source="${kv#*=}" ;;
      teammate_id=*) teammate_id="${kv#*=}" ;;
      status=*)      status="${kv#*=}" ;;
      session=*)     session="${kv#*=}" ;;
      name=*)        name="${kv#*=}" ;;
      agent_id=*)    agent_id="${kv#*=}" ;;
      launched_at=*) launched_at="${kv#*=}" ;;
      deliverable=*) deliverable="${kv#*=}" ;;
      duration=*)    duration="${kv#*=}" ;;
      progress=*)    progress="${kv#*=}" ;;
      claims=*)      claims="${kv#*=}" ;;
      cadence=*)     cadence="${kv#*=}" ;;
      waiver=*)      waiver="${kv#*=}" ;;
      tool_use_id=*) tool_use_id="${kv#*=}" ;;
      # S18, AC-22: present-if-passed, like the real writer's three instrument fields — a
      # caller that never passes `files=` builds a row shaped exactly as every fixture above
      # already does (no key at all), and a caller that does gets the post-S13 shape (the key
      # always present, empty or not).
      files=*)       files="${kv#*=}"; has_files=1 ;;
      *) printf 'mkrow: unknown key %s\n' "$kv" >&2; return 1 ;;
    esac
  done
  [ -n "$launched_at" ] || launched_at="$(iso_ago 60)"
  # THE ROW COMES OFF THE PRODUCTION WRITER (S17, spec AC-25). What stays here is this
  # suite's HOUSE DEFAULTS — the values a case does not name — and the unknown-key refusal,
  # which `roster_row` now makes for real rather than by this wrapper's own `case`.
  #
  # `files=` (S18) and `teammate_id=` are PRESENT-IF-PASSED, which is the writer's own rule
  # and the reason both can be added by naming them rather than by appending a segment by
  # hand. That is also why they are collected into an argument list here instead of four
  # spelled-out calls: the writer decides where each field SITS on the row, so a caller only
  # has to decide whether it is there at all.
  local _mkrow_args
  _mkrow_args=( status="$status" session="$session" name="$name" agent_id="$agent_id"
                launched_at="$launched_at" subagent_type="$subagent_type" model="$model"
                deliverable="$deliverable" source="$source" duration="$duration"
                progress="$progress" claims="$claims" cadence="$cadence" waiver="$waiver"
                tool_use_id="$tool_use_id" )
  if [ "$has_files" -eq 1 ]; then _mkrow_args+=( files="$files" ); fi
  if [ -n "$teammate_id" ]; then _mkrow_args+=( teammate_id="$teammate_id" ); fi
  roster_row_fixture "${_mkrow_args[@]}"
}

roster_of() { printf '%s/.bionic/tmp/roster-%s.state' "$1" "${2:-$SID}"; }

new_roster() {  # <repo> [sid]
  roster_header > "$(roster_of "$1" "${2:-$SID}")"
  # THE ROSTER AND THE ENGAGEMENT MARKER TRAVEL TOGETHER (task-engaged-session): a roster
  # exists because an engaged session dispatched, and this gate asks `engaged_session`
  # before it looks for a roster at all. Without the marker every assertion in this file
  # would be satisfied by a hook that exits at its first line. §E drives the other
  # direction, on the same fixtures.
  : > "$1/.bionic/tmp/engaged-${2:-$SID}.state"
}

add_row() {  # <repo> <key=value>...
  local repo="$1"; shift
  mkrow "$@" >> "$(roster_of "$repo" "$SID")"
}

# The idempotency marker the sweep appends. It rides IN the roster file under its own schema
# prefix, which every roster reader in the fleet filters on (`roster-state/v1|`), so a swept
# line is inert to all of them and cannot outlive the roster it belongs to.
swept_lines() {  # <repo> -> the marker lines, one per verdicted row
  /usr/bin/grep "^${SWEPT_SCHEMA}|" "$(roster_of "$1")" 2>/dev/null
}
swept_count() {  # <repo>
  swept_lines "$1" | /usr/bin/grep -c '|' | tr -d ' '
}

# An ACTIVE wave: the fence-aware `## SDLC State` / `current:` marker the evidence gate,
# stop-guard and dispatch-preflight all read.
plan_active() {  # <repo>
  local d="$1/.bionic/docs/plans/epic-16-landing-contract"
  mkdir -p "$d"
  cat > "$d/wave-01-landing-contract.plan.md" <<'PLAN'
---
governing-skill: superpowers:writing-plans
sdlc-step: 4
canonical_sdlc_version: 14
---

# Wave 01 — landing contract

## SDLC State

integration-branch: main
current: 4
PLAN
}

# A plan whose ONLY `## SDLC State` section is inside a fence: documentation, invisible to
# the parser, so no wave is active. The trap this shape encodes is on the record in
# .claude/rules/hook-authoring.md.
plan_fenced_only() {  # <repo>
  local d="$1/.bionic/docs/plans/epic-16-landing-contract"
  mkdir -p "$d"
  cat > "$d/wave-01-landing-contract.plan.md" <<'PLAN'
---
governing-skill: superpowers:writing-plans
---

# How a plan documents its own format

```
## SDLC State

current: 4
```
PLAN
}

make_repo() {  # <label> -> repo path
  local r="$SANDBOX/$1"
  mkdir -p "$r/.bionic/tmp"
  ( cd "$r" && git init -q . 2>/dev/null )
  printf '%s' "$r"
}

# The standard fixture: an active wave, a roster, and nothing delivered.
make_wave_repo() {  # <label> -> repo path
  local r
  r="$(make_repo "$1")"
  plan_active "$r"
  new_roster "$r"
  printf '%s' "$r"
}

deliver() {  # <repo> <relative path> — a real artifact, written now (after launched_at)
  local p="$1/$2"
  mkdir -p "$(dirname "$p")"
  printf 'the report\n' > "$p"
}

# ---------- git fixtures for the Files: reconciliation (S18, AC-22) ----------
#
# A REAL WORKTREE, REAL COMMITS, REAL git diff/merge-base — every other fixture in this file
# is a synthesized roster line because the gate's OWN subject (the sweep, the landing verdict)
# never touches git. This one does: the reconciliation IS a git operation, and a fixture that
# faked its answer would leave exactly the production path this slice adds unverified (rule:
# seam-blindness — a seam substituting the value under test proves nothing about it).
export GIT_CONFIG_GLOBAL=/dev/null
export GIT_CONFIG_SYSTEM=/dev/null
export GIT_CONFIG_NOSYSTEM=1
export GIT_TERMINAL_PROMPT=0

git_id() { git -C "$1" config user.email "test@example.invalid"; git -C "$1" config user.name "Bionic Test"; }

# The main checkout: one commit on a branch named `main` (forced, so the fixture is
# deterministic regardless of the machine's init.defaultBranch), which is what
# `git -C <repo> rev-parse --abbrev-ref HEAD` — the branch the reconciliation merge-bases
# against — reads back.
make_git_wave_repo() {  # <label> -> repo path
  local r
  r="$(make_wave_repo "$1")"
  git -C "$r" symbolic-ref HEAD refs/heads/main
  git_id "$r"
  printf '.bionic\n.bionic/\n.worktrees/\n' > "$r/.gitignore"
  echo base > "$r/base.txt"
  git -C "$r" add .gitignore base.txt
  git -C "$r" commit -q -m base
  printf '%s' "$r"
}

# A linked worktree at .worktrees/<name>, branched off the repo's current HEAD — the same
# place `worktree_for_row` (payload/scripts/lib/worktree.sh) looks and spawn-worktree.sh
# creates one. <name> doubles as the roster row's `name=` in every case but §16d, so the
# primary (case-preserving) resolution path is what most of this section exercises.
make_slice_tree() {  # <repo> <name> -> worktree path
  local r="$1" name="$2" wt="$1/.worktrees/$2"
  git -C "$r" worktree add -q "$wt" -b "wt/$name" >/dev/null 2>&1
  git_id "$wt"
  printf '%s' "$wt"
}

# One commit in the worktree touching every path given.
commit_files() {  # <worktree> <message> <path>...
  local wt="$1" msg="$2" p
  shift 2
  for p in "$@"; do
    mkdir -p "$(dirname "$wt/$p")"
    echo content >> "$wt/$p"
  done
  git -C "$wt" add "$@"
  git -C "$wt" commit -q -m "$msg"
}

# ---------- running the gate ----------
#
# Sets OUT_STDOUT / OUT_STDERR / RC. Bounded: a gate that hangs inside a Stop hook is a
# defect, and a suite that hangs on it would wedge `bash tests/run.sh`.
# THE ENVIRONMENT AGREES WITH THE PAYLOAD, because on the machine it does (A-probe-2: a
# plain /clear re-keys env, payload and pid file together). Since bionic 1.4.0 the hook
# takes its session id from lib/session.sh, where the env value is primary — so a driver
# that left the runner's own CLAUDE_CODE_SESSION_ID in the environment would be driving a
# DIVERGENCE, not a session, and every roster filename below would be built from the
# wrong key. A payload with no session key exports an empty one, which is what keeps the
# no-session-key arms reaching the fail direction they pin.
run_gate() {  # <gate path> <payload json>
  local gate="$1" json="$2"
  local _sid; _sid=$(printf '%s' "$json" | jq -r '.session_id // ""' 2>/dev/null) || _sid=""
  printf '%s' "$json" > "$SANDBOX/payload.json"
  ( exec env CLAUDE_CODE_SESSION_ID="$_sid" bash "$gate" < "$SANDBOX/payload.json" ) \
    > "$SANDBOX/gate.out" 2> "$SANDBOX/gate.err" &
  local pid=$!
  BG_PIDS="$BG_PIDS $pid"
  local waited=0
  while kill -0 "$pid" 2>/dev/null && [ "$waited" -lt 200 ]; do
    sleep 0.1; waited=$((waited + 1))
  done
  if kill -0 "$pid" 2>/dev/null; then
    kill -9 "$pid" 2>/dev/null
    RC=124
  else
    wait "$pid"; RC=$?
  fi
  OUT_STDOUT="$(cat "$SANDBOX/gate.out")"
  OUT_STDERR="$(cat "$SANDBOX/gate.err")"
}

# ================================================================= Section 1
section "Section 1: a LANDED row with an unmet contract refuses the turn's end"

R1="$(make_wave_repo r1)"
add_row "$R1" name=w1-s5 agent_id="$AID_A" deliverable=.bionic/docs/record/never.md \
  launched_at="$(iso_ago 600)"

# No live task carries this agent's id, so it has landed — which is the whole of the
# landed/live discrimination (T4b §2.2: background_tasks answers "who is still running",
# never "who ran and finished").
run_gate "$GATE" "$(stop_payload "$R1" "$SID" false)"
expect_status "1a: a landed UNMET contract refuses the stop (exit 2)" "2" "$RC"
expect_empty "1a: the refusal goes to stderr, never stdout" "$OUT_STDOUT"

# IDEMPOTENT. Stop fires once per orchestrator TURN and a landed row stays landed forever,
# so a gate that re-verdicted would refuse every turn end for the rest of the session over
# one agent's failure — the false-alarm shape this machinery exists to end.
run_gate "$GATE" "$(stop_payload "$R1" "$SID" false)"
expect_status "1b: the SAME row is not verdicted twice — the second Stop passes" "0" "$RC"
expect_empty "1b: …and on stderr" "$OUT_STDERR"
expect_eq "1b: …and exactly one marker was written, not two" "1" "$(swept_count "$R1")"
expect_contains "1b: …naming the agent id it closed" "agent_id=$AID_A" "$(swept_lines "$R1")"
expect_contains "1b: …and the state it recorded" "state=UNMET" "$(swept_lines "$R1")"

# BLOCKS ONCE on re-entry too: Claude Code re-enters the stop with stop_hook_active true
# after a hook blocked it, and a gate that refused again would wedge the turn.
R1B="$(make_wave_repo r1b)"
add_row "$R1B" name=w1-s5 agent_id="$AID_A" deliverable=.bionic/docs/record/never.md \
  launched_at="$(iso_ago 600)"
run_gate "$GATE" "$(stop_payload "$R1B" "$SID" true)"
expect_status "1c: stop_hook_active true passes the same unmet contract" "0" "$RC"
expect_empty "1c: …silently" "$OUT_STDERR"
expect_eq "1c: …and takes no verdict at all, so the row is still owed one" \
  "0" "$(swept_count "$R1B")"

# ================================================================= Section 2
section "Section 2: a landed row that DID deliver is closed, silently"

R2="$(make_wave_repo r2)"
add_row "$R2" name=met-row agent_id="$AID_A" deliverable=.bionic/docs/record/landed.md \
  launched_at="$(iso_ago 600)"
deliver "$R2" .bionic/docs/record/landed.md

run_gate "$GATE" "$(stop_payload "$R2" "$SID" false)"
expect_status "2a: a landed MET contract passes" "0" "$RC"
expect_empty "2a: …silently — a met contract is not news" "$OUT_STDERR"
expect_eq "2a: …and is marked swept, so it is never re-read" "1" "$(swept_count "$R2")"
expect_contains "2a: …recording the state the verb computed" "state=MET" "$(swept_lines "$R2")"

# ================================================================= Section 3
section "Section 3: STILL-LIVE by the payload — a running agent is skipped, not judged"

R3="$(make_wave_repo r3)"
add_row "$R3" name=live-row agent_id="$AID_A" deliverable=.bionic/docs/record/never.md \
  launched_at="$(iso_ago 600)"

# The agent is IN background_tasks: it has not landed, so there is nothing to hold it to yet.
run_gate "$GATE" "$(stop_payload "$R3" "$SID" false "$AID_A")"
expect_status "3a: a row still in background_tasks passes" "0" "$RC"
expect_empty "3a: …silently" "$OUT_STDERR"
expect_eq "3a: …and is NOT marked swept — its verdict is still owed" "0" "$(swept_count "$R3")"

# …and when it lands, the same roster is judged for the first time.
run_gate "$GATE" "$(stop_payload "$R3" "$SID" false)"
expect_status "3b: once it drops out of background_tasks it is judged, and refuses" "2" "$RC"
expect_eq "3b: …and is marked swept exactly once" "1" "$(swept_count "$R3")"

# A live sibling does not shield a landed row, and a landed sibling does not implicate a
# live one: the discrimination is per row, by id.
R3C="$(make_wave_repo r3c)"
add_row "$R3C" name=landed-one agent_id="$AID_A" deliverable=.bionic/docs/record/never.md \
  launched_at="$(iso_ago 600)" tool_use_id=toolu_ONE
add_row "$R3C" name=flying-one agent_id="$AID_B" deliverable=.bionic/docs/record/never2.md \
  launched_at="$(iso_ago 600)" tool_use_id=toolu_TWO
run_gate "$GATE" "$(stop_payload "$R3C" "$SID" false "$AID_B")"
expect_status "3c: one landed and one live — the landed one refuses" "2" "$RC"
expect_eq "3c: …with one marker, for the landed row alone" "1" "$(swept_count "$R3C")"

# ================================================================= Section 4
section "Section 4: relevance and ambiguity — every way out is silent"

R4="$(make_wave_repo r4)"
add_row "$R4" name=w1-s5 agent_id="$AID_A" deliverable=.bionic/docs/record/never.md \
  launched_at="$(iso_ago 600)"

# A SubagentStop whose id belongs to a SUBAGENT row is not this arm's business either: the
# roster's responsibility partition gives async dispatches to the Stop-sweep, which judges
# them by disappearance from `background_tasks[]`, and teammates to the SubagentStop arm.
# Verdicting here would not merely duplicate the sweep — it would STEAL the refusal, since
# the marker this arm writes is what tells the sweep a row is answered for, and the sweep's
# refusal is the one that reaches the orchestrator (Section 12's rationale).
run_gate "$GATE" "$(substop_payload "$R4" "$SID" "$AID_A" general-purpose false)"
expect_status "4a: a SubagentStop over a SUBAGENT row belongs to the sweep — pass" "0" "$RC"
expect_empty "4a: …silently" "$OUT_STDERR"
expect_eq "4a: …and nothing is swept out from under the sweep" "0" "$(swept_count "$R4")"

run_gate "$GATE" "$(stop_payload "" "$SID" false)"
expect_status "4b: no cwd — the repo is unresolvable, pass" "0" "$RC"

run_gate "$GATE" "$(stop_payload "$SANDBOX/not-a-repo" "$SID" false)"
expect_status "4c: a cwd outside any repo passes" "0" "$RC"

run_gate "$GATE" "$(stop_payload "$R4" "" false)"
expect_status "4d: no session key — no roster to scope to, pass" "0" "$RC"

run_gate "$GATE" "$(stop_payload "$R4" "$SID_B" false)"
expect_status "4e: another session's Stop reads that session's (absent) roster, pass" "0" "$RC"

run_gate "$GATE" "not json at all"

R4B="$(make_repo r4b)"
plan_active "$R4B"
run_gate "$GATE" "$(stop_payload "$R4B" "$SID" false)"
expect_status "4g: no roster file at all passes" "0" "$RC"

# THE UNJOINABLE ROW. `agent_id=` is empty until hooks/execution-recorder.sh's roster arm
# completes the launch row, and a row that never got one cannot be placed on either side of
# the landed/live line. Judging it would hold an agent to a contract on the strength of a
# field we do not have; the ambiguity direction is the same as every other one here.
R4C="$(make_wave_repo r4c)"
add_row "$R4C" name=never-spawned agent_id= status=intended \
  deliverable=.bionic/docs/record/never.md launched_at="$(iso_ago 600)"
run_gate "$GATE" "$(stop_payload "$R4C" "$SID" false)"

# THE MONOTONE SEQUENCE ITSELF (t6-review.md F-3 sub-gap): `intended` (agent_id empty) then
# `identified` (agent_id filled) for the SAME contract, appended as two roster rows the way
# hooks/dispatch-preflight.sh and hooks/execution-recorder.sh really write them — the
# two-row lifecycle the monotone `if (aid != "") agent[name] = aid` rule exists for. 4h
# drove an all-empty row; 8c (below) drives two ALREADY-filled duplicate rows; neither drove
# the TRANSITION. Subagent-shaped (no `teammate_id=`), so this is the sweep's row, not the
# SubagentStop arm's (session-20260815 T2 teammate-skip).
R4I="$(make_wave_repo r4i)"
add_row "$R4I" name=w4-t2mono status=intended agent_id= \
  deliverable=.bionic/docs/record/never-mono.md tool_use_id=toolu_MONO \
  launched_at="$(iso_ago 600)"
add_row "$R4I" name=w4-t2mono status=identified agent_id="$AID_A" \
  deliverable=.bionic/docs/record/never-mono.md tool_use_id=toolu_MONO \
  launched_at="$(iso_ago 600)"
run_gate "$GATE" "$(stop_payload "$R4I" "$SID" false)"
expect_status "4i: intended-then-identified — the LATER row's agent_id places it, and it refuses on its own contract" \
  "2" "$RC"
expect_contains "4i: …and the marker keys on the row that actually carries an id" \
  "agent_id=$AID_A" "$(swept_lines "$R4I")"

# THE DISCRIMINATING HALF: a copy of the gate with the monotone guard INVERTED (`aid == ""`
# instead of `aid != ""`) — the classic off-by-negation typo. Against the identical fixture
# it takes the EMPTY row's non-answer, the candidate's AID goes blank, and the gate's own
# `[ -n "$AID" ] ... || continue` drops the row silently — a genuinely UNMET contract
# passes. The mutant copy sits beside a real sweeper, the production resolution.
MONODIR="$SANDBOX/hooks-mono-mutant"
mkdir -p "$MONODIR"
cp "$HOOKS_DIR/session-sweeper.sh" "$MONODIR/session-sweeper.sh"
# The awk below rewrites ONE line of the shipped gate, so that line is this mutation's
# precondition and it is declared through the framework's `anchor` (cross-gate section
# S19) rather than checked afterwards.
#
# THE PATTERN IS A WHOLE-LINE ERE, not the fixed string it reads like, because the awk
# compares `$0` against the WHOLE line: a fixed-string anchor is a substring test and
# would still match a reindented copy the awk no longer touches, leaving a mutant that
# is byte-identical to the shipped gate and every row below it green against it. The
# count was measured against the shipped gate before this call was written.
anchor -E "$GATE" '^    if \(aid != ""\) agent\[name\] = aid$' 1
awk '{
       if ($0 == "    if (aid != \"\") agent[name] = aid") {
         print "    if (aid == \"\") agent[name] = aid"
         next
       }
       print
     }' "$GATE" > "$MONODIR/landing-gate.sh"

R4I_MUT="$(make_wave_repo r4i-mut)"
add_row "$R4I_MUT" name=w4-t2mono status=intended agent_id= \
  deliverable=.bionic/docs/record/never-mono.md tool_use_id=toolu_MONO \
  launched_at="$(iso_ago 600)"
add_row "$R4I_MUT" name=w4-t2mono status=identified agent_id="$AID_A" \
  deliverable=.bionic/docs/record/never-mono.md tool_use_id=toolu_MONO \
  launched_at="$(iso_ago 600)"
run_gate "$MONODIR/landing-gate.sh" "$(stop_payload "$R4I_MUT" "$SID" false)"
expect_status "4i-mut: with the guard inverted, the SAME genuinely-UNMET contract passes silently" \
  "0" "$RC"
expect_eq "4i-mut: …and nothing is marked — the row was dropped by the blank-AID skip, never judged" \
  "0" "$(swept_count "$R4I_MUT")"

# ================================================================= Section 5
section "Section 5: ENGAGEMENT, not the plan, is what holds anyone to anything"

# THE SUBJECT OF THIS SECTION CHANGED AT task-engaged-session. It used to be "no active
# wave — nothing to hold anyone to", scoping the gate by `active_run`. That is the defect
# this wave fixes from the other side: the plan gated every SESSION in the repo, including
# ones that never entered bionic, while a landing contract is owed by the session that
# LAUNCHED the agent — a fact that predates the plan (a run's Step 0 writes the roster
# before it writes the plan) and outlives it (engagement does not end when `current:`
# reaches 9). So the gate reads no plan at all now, and the fixtures below keep their
# shapes with their expectations moved onto the switch that actually scopes them.

R5="$(make_repo r5)"
new_roster "$R5"
add_row "$R5" name=w1-s5 agent_id="$AID_A" deliverable=.bionic/docs/record/never.md \
  launched_at="$(iso_ago 600)"
run_gate "$GATE" "$(stop_payload "$R5" "$SID" false)"
expect_status "5a: no plan at all — an ENGAGED session still owes its verdict" "2" "$RC"
R5_REFUSAL="$OUT_STDERR"

rm -f "$R5/.bionic/tmp/engaged-$SID.state"
run_gate "$GATE" "$(stop_payload "$R5" "$SID" false)"
expect_status "5a-neg: the same unmet roster, unengaged, passes" "0" "$RC"
expect_empty "5a-neg: …silently" "$OUT_STDERR"

# a SYMLINK at the marker path reads as ABSENT, never followed.
R5_DECOY="$SANDBOX/r5-decoy-marker"; printf 'plan=none\n' > "$R5_DECOY"
ln -s "$R5_DECOY" "$R5/.bionic/tmp/engaged-$SID.state"
run_gate "$GATE" "$(stop_payload "$R5" "$SID" false)"
expect_status "5a-sym: a symlink at the marker path is not an engagement" "0" "$RC"
expect_empty "5a-sym: …silently" "$OUT_STDERR"
rm -f "$R5/.bionic/tmp/engaged-$SID.state"

# ANOTHER session's marker is not this session's.
: > "$R5/.bionic/tmp/engaged-$SID_B.state"
run_gate "$GATE" "$(stop_payload "$R5" "$SID" false)"
expect_status "5a-foreign: another session's marker is not this session's engagement" "0" "$RC"
rm -f "$R5/.bionic/tmp/engaged-$SID_B.state"

# restored, the refusal returns byte for byte. ON A FRESH ROSTER, because this gate blocks
# ONCE per row: the first refusal above journalled its own `landing-swept/v1|` marker, and
# re-driving the same file would compare the refusal against the silence that marker is
# supposed to produce.
R5BACK="$(make_repo r5back)"
new_roster "$R5BACK"
add_row "$R5BACK" name=w1-s5 agent_id="$AID_A" deliverable=.bionic/docs/record/never.md \
  launched_at="$(iso_ago 600)"
run_gate "$GATE" "$(stop_payload "$R5BACK" "$SID" false)"
expect_eq "5a-back: engaged with no plan, the refusal is byte-identical to 5a" "$R5_REFUSAL" "$OUT_STDERR"

R5B="$(make_repo r5b)"
plan_fenced_only "$R5B"
new_roster "$R5B"
add_row "$R5B" name=w1-s5 agent_id="$AID_A" deliverable=.bionic/docs/record/never.md \
  launched_at="$(iso_ago 600)"
run_gate "$GATE" "$(stop_payload "$R5B" "$SID" false)"
expect_status "5b: a fenced-only SDLC State changes nothing either way — the roster decides" "2" "$RC"

# ================================================================= Section 6
section "Section 6: fail-open — every way the verdict can fail to answer"

# The gate resolves the sweeper as its own sibling. The cases below run a COPY of the gate
# from a directory whose sibling differs, which is the production resolution path under a
# different filesystem, not a substituted seam.
R6="$(make_wave_repo r6)"
add_row "$R6" name=w1-s5 agent_id="$AID_A" deliverable=.bionic/docs/record/never.md \
  launched_at="$(iso_ago 600)"

NOSWEEP="$SANDBOX/hooks-nosweeper"
mkdir -p "$NOSWEEP"
cp "$GATE" "$NOSWEEP/landing-gate.sh" 2>/dev/null
run_gate "$NOSWEEP/landing-gate.sh" "$(stop_payload "$R6" "$SID" false)"
expect_status "6a: the sweeper script is absent — pass, do not block on a verdict we cannot take" "0" "$RC"
expect_eq "6a: …and mark nothing swept on an answer we never got" "0" "$(swept_count "$R6")"

BADSWEEP="$SANDBOX/hooks-badsweeper"
mkdir -p "$BADSWEEP"
cp "$GATE" "$BADSWEEP/landing-gate.sh" 2>/dev/null
printf '#!/bin/bash\nexit 7\n' > "$BADSWEEP/session-sweeper.sh"
chmod +x "$BADSWEEP/session-sweeper.sh"
run_gate "$BADSWEEP/landing-gate.sh" "$(stop_payload "$R6" "$SID" false)"
expect_status "6b: the sweeper errors — pass" "0" "$RC"
expect_eq "6b: …and the row stays owed a verdict" "0" "$(swept_count "$R6")"

QUIETSWEEP="$SANDBOX/hooks-quietsweeper"
mkdir -p "$QUIETSWEEP"
cp "$GATE" "$QUIETSWEEP/landing-gate.sh" 2>/dev/null
printf '#!/bin/bash\nexit 1\n' > "$QUIETSWEEP/session-sweeper.sh"
chmod +x "$QUIETSWEEP/session-sweeper.sh"
run_gate "$QUIETSWEEP/landing-gate.sh" "$(stop_payload "$R6" "$SID" false)"
expect_eq "6c: …and nothing is marked closed on a line that was never printed" \
  "0" "$(swept_count "$R6")"

# A symlinked roster makes the verdict verb REFUSE (exit 2). That is the gate's fail-open
# path, and it is the one direction a hostile repo could otherwise use to aim this gate: it
# must never turn a refusal into a block. The gate refuses to WRITE through the link too.
R6B="$(make_repo r6b)"
plan_active "$R6B"
REAL_ROSTER="$SANDBOX/elsewhere-roster.state"
roster_header > "$REAL_ROSTER"
mkrow name=w1-s5 agent_id="$AID_A" deliverable=.bionic/docs/record/never.md \
  launched_at="$(iso_ago 600)" >> "$REAL_ROSTER"
ln -s "$REAL_ROSTER" "$(roster_of "$R6B")"
run_gate "$GATE" "$(stop_payload "$R6B" "$SID" false)"
expect_status "6d: a symlinked roster — the gate passes, never blocks" "0" "$RC"

# ================================================================= Section 7
section "Section 7: the join is by agent id — an UNNAMED dispatch is judged like any other"

# `name` is optional at dispatch, so the roster's `name=` can be empty; the sweeper folds
# such a row under `(unnamed)`. The join that decides landed-vs-live is the AGENT ID, which
# every dispatch has, so an unnamed one is held to its contract exactly like a named one.
# This is the §5.1 defect closed: nothing on this path reads `agent_type`.
R7="$(make_wave_repo r7)"
add_row "$R7" name= agent_id="$AID_A" deliverable=.bionic/docs/record/never.md \
  launched_at="$(iso_ago 600)"
run_gate "$GATE" "$(stop_payload "$R7" "$SID" false)"
expect_status "7a: an unnamed dispatch still refuses on its own contract" "2" "$RC"
expect_contains "7a: …and the marker keys on the id, which is what it actually has" \
  "agent_id=$AID_A" "$(swept_lines "$R7")"

# The same row, still in flight, is skipped by the same join.
R7B="$(make_wave_repo r7b)"
add_row "$R7B" name= agent_id="$AID_A" deliverable=.bionic/docs/record/never.md \
  launched_at="$(iso_ago 600)"
run_gate "$GATE" "$(stop_payload "$R7B" "$SID" false "$AID_A")"
expect_status "7b: …and is skipped while its id is still in background_tasks" "0" "$RC"

# ================================================================= Section 8
section "Section 8: the states the sweep must never refuse"

R8="$(make_wave_repo r8)"
# FIXTURE FIDELITY (wave-01 Step-6 review S-1): a genuine waiver row names NO artifact — the
# wall's waiver label reads "why this dispatch produces nothing durable".
add_row "$R8" name=waived-row agent_id="$AID_A" waiver="exploratory probe" \
  launched_at="$(iso_ago 600)" tool_use_id=toolu_WAIVED
run_gate "$GATE" "$(stop_payload "$R8" "$SID" false)"

# STILL-LIVE by the ROW's own claim: the verdict verb owns that judgment, and the gate
# honours it rather than reading "not delivered" as a failure.
R8B="$(make_wave_repo r8b)"
MARKER="$SANDBOX/bionic-landing-gate-marker-91744.sh"
printf '#!/bin/bash\nsleep 60\n' > "$MARKER"
chmod +x "$MARKER"
"$MARKER" & MARKER_PID=$!
BG_PIDS="$BG_PIDS $MARKER_PID"
add_row "$R8B" name=claimed-row agent_id="$AID_A" deliverable=.bionic/docs/record/never.md \
  claims="$MARKER" launched_at="$(iso_ago 600)"
run_gate "$GATE" "$(stop_payload "$R8B" "$SID" false)"
expect_status "8b: a STILL-LIVE row passes" "0" "$RC"
expect_empty "8b: …silently" "$OUT_STDERR"
kill -9 "$MARKER_PID" 2>/dev/null

# AMBIGUOUS: two contracts share one name, so no reader can tell whose artifact is whose.
R8C="$(make_wave_repo r8c)"
deliver "$R8C" .bionic/docs/record/first.md
add_row "$R8C" name=dup agent_id="$AID_A" deliverable=.bionic/docs/record/first.md \
  tool_use_id=toolu_01FIRST launched_at="$(iso_ago 900)"
add_row "$R8C" name=dup agent_id="$AID_A" deliverable=.bionic/docs/record/second.md \
  tool_use_id=toolu_01SECOND launched_at="$(iso_ago 600)"
run_gate "$GATE" "$(stop_payload "$R8C" "$SID" false)"
expect_status "8c: an ambiguous name refuses nobody" "0" "$RC"
expect_empty "8c: …silently, naming no artifact that may not be its job" "$OUT_STDERR"

# ================================================================= Section 9
section "Section 9: an ACKED row is closed for every reader (epic-16 w2 S3, R2)"

SWEEPER_BIN="$(cd "$(dirname "$GATE")" && pwd)/session-sweeper.sh"
ack_row() {  # <repo> <name>
  ( cd "$1" && CLAUDE_CODE_SESSION_ID="$SID" bash "$SWEEPER_BIN" ack "$2" ) >/dev/null 2>&1
  return 0
}

R9="$(make_wave_repo r9)"
add_row "$R9" name=w2-s3 agent_id="$AID_A" deliverable=.bionic/docs/record/never.md \
  launched_at="$(iso_ago 600)"
run_gate "$GATE" "$(stop_payload "$R9" "$SID" false)"
expect_status "9a: precondition — an unacked UNMET contract refuses" "2" "$RC"

R9B="$(make_wave_repo r9b)"
add_row "$R9B" name=w2-s3 agent_id="$AID_A" deliverable=.bionic/docs/record/never.md \
  launched_at="$(iso_ago 600)"
ack_row "$R9B" w2-s3
run_gate "$GATE" "$(stop_payload "$R9B" "$SID" false)"
expect_status "9b: once acked, the same sweep passes" "0" "$RC"
expect_empty "9c: …silently — the orchestrator already accounted for it" "$OUT_STDERR"
expect_eq "9d: …and the row is still marked swept, so it is asked about once" \
  "1" "$(swept_count "$R9B")"

# ================================================================= Section 10
section "Section 10: the sweep records only its own marker, and only in the roster"

R10="$(make_wave_repo r10)"
add_row "$R10" name=mine agent_id="$AID_A" deliverable=.bionic/docs/record/mine.md \
  launched_at="$(iso_ago 600)" tool_use_id=toolu_MINE
deliver "$R10" .bionic/docs/record/mine.md
BEFORE="$(ls -A "$R10/.bionic/tmp" | sort)"
run_gate "$GATE" "$(stop_payload "$R10" "$SID" false)"
AFTER="$(ls -A "$R10/.bionic/tmp" | sort)"
expect_eq "10a: the sweep creates no state file of its own" "$BEFORE" "$AFTER"
expect_eq "10c: …and exactly one marker line beside it" "1" "$(swept_count "$R10")"

# THE MARKER IS INERT TO THE ROSTER'S OWN READER. The sweeper folds `roster-state/v1|` rows
# and nothing else, so the verdict it computes after a sweep is the verdict it computed
# before one — a marker that changed an answer would be this gate quietly acquiring the
# authority ADR-003 denies it.
R10_VERDICT=$( cd "$R10" && CLAUDE_CODE_SESSION_ID="$SID" bash "$SWEEPER_BIN" verdict mine 2>/dev/null \
               | /usr/bin/grep -F 'landing-verdict/v1|' | head -1 | tr '|' '\n' \
               | /usr/bin/grep '^state=' | cut -d= -f2- )

# ================================================================= Section 11
section "Section 11: the payload session key is shape-checked before it becomes a path"

# `roster-${SID}.state` interpolates the payload's session id straight into a path the sweep
# now WRITES to, and the symlink guards check the state directory and the exact filenames —
# so a key carrying path separators leaves the guarded directory entirely rather than
# tripping a guard.
R11="$(make_wave_repo r11)"
mkdir -p "$R11/.bionic/tmp/roster-x" "$R11/planted"
SID_TRAVERSAL='x/../../../planted/evil'
PLANTED="$R11/planted/evil.state"
roster_header > "$PLANTED"
mkrow name=w1-s5 session="$SID_TRAVERSAL" agent_id="$AID_A" \
  deliverable=.bionic/docs/record/never.md launched_at="$(iso_ago 600)" >> "$PLANTED"
run_gate "$GATE" "$(stop_payload "$R11" "$SID_TRAVERSAL" false)"
expect_status "11b: a session key carrying path separators is not a session key — pass" "0" "$RC"
expect_absent "11d: …and no marker is written into it" "landing-swept" "$(cat "$PLANTED")"

# ================================================================= Section 12
section "Section 12: TEAMMATES LAND AT SubagentStop (session-20260815 T2, R1/AC-2)"

# WHY A SECOND ARM AND NOT A BETTER JOIN. The sweep's discrimination is "a roster row whose
# agent_id is absent from background_tasks[] has landed", and for a named teammate that
# predicate is wrong in BOTH directions (t1-probe-report.md §2.3): the three id namespaces a
# teammate carries never join — the addressing form at dispatch, the transcript form on
# SubagentStart/Stop, and an opaque token in background_tasks[] — and the teammate's row never
# leaves that array at all, so a filled agent_id would read as LANDED on the first Stop after
# dispatch, 2.8 s in, while the teammate is still working. SubagentStop is the transition
# itself, delivered with every fact the verdict needs in one payload: no join to reconstruct,
# no disappearance to infer.
#
# The arm reuses the sweep's own machinery unchanged — the same `session-sweeper.sh verdict`
# verb, the same landing-swept/v1 marker through the same append, the same refusal text — so
# what is new here is WHICH ROW is judged and WHEN, and nothing about how.
TEAM_AID="aw2mate-fdaa80c4b3cb703f"        # transcript form: `a` + name + `-` + 16 hex (t1 §2.2)
TEAM_ADDR="w2mate@session-3b51bef0"        # addressing form, the field that says "teammate"
TEAM_BG="[$(bg_teammate t5triyxvo)]"       # its own still-running row, for the whole session

R12="$(make_wave_repo r12)"
add_row "$R12" name=w2mate agent_id="$TEAM_AID" teammate_id="$TEAM_ADDR" \
  deliverable=.bionic/docs/record/mate.md launched_at="$(iso_ago 600)"
deliver "$R12" .bionic/docs/record/mate.md
run_gate "$GATE" "$(substop_payload "$R12" "$SID" "$TEAM_AID" w2mate false "$TEAM_BG")"
expect_status "12a: a teammate that delivered lands MET, and passes" "0" "$RC"
expect_empty "12a: …silently — a met contract is not news" "$OUT_STDERR"
expect_eq "12a: …and is marked swept, through the same append the sweep uses" \
  "1" "$(swept_count "$R12")"
expect_contains "12a: …recording the state the verb computed" "state=MET" "$(swept_lines "$R12")"
expect_contains "12a: …keyed by the transcript-form id ARM 3 filled in" \
  "agent_id=$TEAM_AID" "$(swept_lines "$R12")"

R12B="$(make_wave_repo r12b)"
add_row "$R12B" name=w2mate agent_id="$TEAM_AID" teammate_id="$TEAM_ADDR" \
  deliverable=.bionic/docs/record/never.md launched_at="$(iso_ago 600)"
run_gate "$GATE" "$(substop_payload "$R12B" "$SID" "$TEAM_AID" w2mate false "$TEAM_BG")"
expect_status "12b: a teammate that did NOT deliver is refused (exit 2)" "2" "$RC"
expect_empty "12b: the refusal goes to stderr, never stdout" "$OUT_STDOUT"
expect_contains "12b: …and the row is marked, so it is asked about once" \
  "state=UNMET" "$(swept_lines "$R12B")"

# ONCE PER ROW, EVER — the same promise the sweep makes. A blocked SubagentStop is re-entered
# with stop_hook_active true (the harness's own guidance for Stop/SubagentStop hooks, read out
# of the shipped binary), and the teammate can stop again after that: neither re-entry may
# re-refuse, or the agent is wedged in a loop it has no way out of.
run_gate "$GATE" "$(substop_payload "$R12B" "$SID" "$TEAM_AID" w2mate true "$TEAM_BG")"
expect_status "12c: the blocked re-entry (stop_hook_active) passes" "0" "$RC"
expect_empty "12c: …silently" "$OUT_STDERR"
expect_eq "12c: …and takes no second verdict" "1" "$(swept_count "$R12B")"
run_gate "$GATE" "$(substop_payload "$R12B" "$SID" "$TEAM_AID" w2mate false "$TEAM_BG")"
expect_status "12d: a later SubagentStop for the same marked row passes" "0" "$RC"
expect_empty "12d: …silently" "$OUT_STDERR"
expect_eq "12d: …and writes no second marker" "1" "$(swept_count "$R12B")"

# THE ROW IS STILL IN background_tasks[] IN EVERY CASE ABOVE — that is the fixture's point,
# not an accident (t1 §2.3). This arm must not consult the live set: the event IS the landing.

# THE NAME FALLBACK. `agent_id=` is filled by the recorder's identification arm at
# SubagentStart; if that event was lost, the row is still joinable here because SubagentStop's
# `agent_type` carries the dispatch NAME for a teammate (t1 §2.1 — the field wave-03 read as
# the subagent type, which it is for an async dispatch and is not for a teammate). The marker
# then keys on the id the PAYLOAD carries, which is the same transcript form the join would
# have written, so the row is still answered for exactly once.
R12F="$(make_wave_repo r12f)"
add_row "$R12F" name=w2mate agent_id= status=confirmed teammate_id="$TEAM_ADDR" \
  deliverable=.bionic/docs/record/never.md launched_at="$(iso_ago 600)"
run_gate "$GATE" "$(substop_payload "$R12F" "$SID" "$TEAM_AID" w2mate false "$TEAM_BG")"
expect_status "12f: an unidentified teammate row is joined by NAME, and refuses" "2" "$RC"
expect_contains "12f: …and the marker keys on the id the payload carried" \
  "agent_id=$TEAM_AID" "$(swept_lines "$R12F")"
run_gate "$GATE" "$(substop_payload "$R12F" "$SID" "$TEAM_AID" w2mate false "$TEAM_BG")"
expect_eq "12f: …once, and not again on the next stop" "1" "$(swept_count "$R12F")"

# THE PHANTOMS. Roughly nine harness-internal SubagentStops arrive per session carrying an
# `agent_type` of "" and an id on no row of ours (t1 §4.6). They are a read to budget for, not
# a correctness problem — but only if a no-match is silent.
R12G="$(make_wave_repo r12g)"
add_row "$R12G" name=w2mate agent_id="$TEAM_AID" teammate_id="$TEAM_ADDR" \
  deliverable=.bionic/docs/record/never.md launched_at="$(iso_ago 600)"
run_gate "$GATE" "$(substop_payload "$R12G" "$SID" "a12b83613c5edc596" "" false "$TEAM_BG")"
expect_status "12g: a phantom SubagentStop matching no roster row passes" "0" "$RC"
expect_empty "12g: …silently" "$OUT_STDERR"
expect_eq "12g: …and marks nothing, so the real row keeps its verdict owed" \
  "0" "$(swept_count "$R12G")"

# The same ways out the sweep has, on the new event.
R12H="$(make_repo r12h)"
new_roster "$R12H"
add_row "$R12H" name=w2mate agent_id="$TEAM_AID" teammate_id="$TEAM_ADDR" \
  deliverable=.bionic/docs/record/never.md launched_at="$(iso_ago 600)"
run_gate "$GATE" "$(substop_payload "$R12H" "$SID" "$TEAM_AID" w2mate false "$TEAM_BG")"
expect_status "12h: no plan — an engaged session's teammate is still held to its contract" "2" "$RC"

# and the same teammate, unengaged, is held to nothing at all.
rm -f "$R12H/.bionic/tmp/engaged-$SID.state"
run_gate "$GATE" "$(substop_payload "$R12H" "$SID" "$TEAM_AID" w2mate false "$TEAM_BG")"
expect_status "12h-neg: …and unengaged, held to nothing" "0" "$RC"
expect_empty "12h-neg: …silently" "$OUT_STDERR"

R12I="$(make_wave_repo r12i)"
add_row "$R12I" name=w2mate agent_id="$TEAM_AID" teammate_id="$TEAM_ADDR" \
  waiver="exploratory probe" launched_at="$(iso_ago 600)"
run_gate "$GATE" "$(substop_payload "$R12I" "$SID" "$TEAM_AID" w2mate false "$TEAM_BG")"
expect_eq "12i: …and is not marked, exactly as the sweep leaves it" "0" "$(swept_count "$R12I")"

# ================================================================= Section 13
section "Section 13: the sweep SKIPS teammate rows — the partition, both halves"

# THIS SKIP IS LOAD-BEARING, not hygiene. Once the recorder's scoped name join fills a
# teammate row's `agent_id` with the transcript form, that id is absent from
# `background_tasks[]` by construction — the array keys teammates under a different namespace
# entirely — so the sweep's landed/live predicate reads EVERY teammate as landed on the first
# Stop after dispatch, 2.8 s in, and turns today's silence into a false refusal on every
# teammate dispatch (t1 §2.3). The two arms partition the roster on one field: rows carrying a
# `teammate_id=` belong to SubagentStop, rows without it to the sweep.
R13="$(make_wave_repo r13)"
add_row "$R13" name=w2mate agent_id="$TEAM_AID" teammate_id="$TEAM_ADDR" \
  deliverable=.bionic/docs/record/never.md launched_at="$(iso_ago 600)"
run_gate "$GATE" "$(stop_payload "$R13" "$SID" false)"
expect_status "13a: a teammate row with a filled id is NOT swept-landed" "0" "$RC"
expect_empty "13a: …and the sweep says nothing about it" "$OUT_STDERR"
expect_eq "13a: …and marks nothing, leaving the verdict to its own event" \
  "0" "$(swept_count "$R13")"

# THE DISCRIMINATING PAIR: the same row, same id, same missing artifact, differing only in the
# field the partition reads. Without it this section would pass over any implementation that
# simply stopped sweeping.
R13B="$(make_wave_repo r13b)"
add_row "$R13B" name=w2mate agent_id="$TEAM_AID" \
  deliverable=.bionic/docs/record/never.md launched_at="$(iso_ago 600)"
run_gate "$GATE" "$(stop_payload "$R13B" "$SID" false)"
expect_status "13b: …while the identical row WITHOUT teammate_id is swept and refuses" "2" "$RC"
expect_eq "13b: …and marked once" "1" "$(swept_count "$R13B")"

# A teammate row does not shield its neighbours: the skip is per row, on the same fold.
R13C="$(make_wave_repo r13c)"
add_row "$R13C" name=w2mate agent_id="$TEAM_AID" teammate_id="$TEAM_ADDR" \
  deliverable=.bionic/docs/record/never.md launched_at="$(iso_ago 600)" tool_use_id=toolu_MATE
add_row "$R13C" name=async-one agent_id="$AID_B" \
  deliverable=.bionic/docs/record/never2.md launched_at="$(iso_ago 600)" tool_use_id=toolu_ASYNC
run_gate "$GATE" "$(stop_payload "$R13C" "$SID" false)"
expect_status "13c: a landed subagent beside a teammate still refuses" "2" "$RC"
expect_eq "13c: …with one marker, for the subagent alone" "1" "$(swept_count "$R13C")"

# ================================================================= Section 14
section "Section 14: crash-safe marks — a sweep killed mid-loop banks every already-decided verdict (T3, AC-3, R3)"

# THE FAILURE THIS CLOSES (t6-review.md F-2, measured). The sweep used to accumulate every
# marker line in a shell variable across the whole loop and write them in ONE append AFTER
# it. A sweep killed mid-loop therefore journalled nothing — the review's own repro killed
# the hook 5s into a 200-candidate sweep (~60 already verdicted) and found zero
# landing-swept lines afterward. Past ~120 candidates the 10s hook timeout saturates the
# same way: the sweep is killed, no marks land, the candidate set is IDENTICAL on the next
# Stop, and it times out again — permanently, with the wall silently inert. The real
# verdict subprocess (~70-90ms/candidate, measured both by the review and locally) is what
# gives this fixture real, unstubbed time to kill into.

R14="$(make_wave_repo r14)"
N14=30
i=1
while [ "$i" -le "$N14" ]; do
  AID14=$(printf 'ak14%013x' "$i")
  add_row "$R14" name="k14-$i" agent_id="$AID14" \
    deliverable=".bionic/docs/record/never-$i.md" launched_at="$(iso_ago 600)" \
    tool_use_id="toolu_K14_$i"
  i=$((i + 1))
done

PAYLOAD14="$SANDBOX/payload14.json"
stop_payload "$R14" "$SID" false > "$PAYLOAD14"

# The session key travels in the environment here for the same reason run_gate puts it
# there: the gate takes it from lib/session.sh, env first, and the roster this section
# kills a sweep over is named after it.
( exec env CLAUDE_CODE_SESSION_ID="$SID" bash "$GATE" < "$PAYLOAD14" ) \
  > "$SANDBOX/gate14.out" 2> "$SANDBOX/gate14.err" &
GATE14_PID=$!
BG_PIDS="$BG_PIDS $GATE14_PID"

# Poll for the FIRST sign of progress WHILE THE PROCESS IS STILL ALIVE, then kill it
# immediately — that is what proves the kill lands mid-loop rather than after the sweep
# would have finished on its own. Bounded at 8s so a hung gate fails the section loudly
# instead of wedging the suite.
SEEN_MIDFLIGHT=0
waited14=0
while [ "$waited14" -lt 400 ]; do
  if ! kill -0 "$GATE14_PID" 2>/dev/null; then
    break
  fi
  CUR14=$(swept_count "$R14")
  if [ "$CUR14" -gt 0 ] 2>/dev/null; then
    kill -9 "$GATE14_PID" 2>/dev/null
    SEEN_MIDFLIGHT=1
    break
  fi
  sleep 0.02
  waited14=$((waited14 + 1))
done
# Make sure the process is really gone before reading the roster's final state — a kill
# signal is delivered, not necessarily reaped, before the next line runs.
wait "$GATE14_PID" 2>/dev/null

MIDFLIGHT_COUNT=$(swept_count "$R14")
expect_eq "14a: the kill really did land mid-loop, with the process still alive" "1" "$SEEN_MIDFLIGHT"
expect_gt "14b: at least one already-decided verdict was banked before the kill" \
  "$MIDFLIGHT_COUNT" "0"

# THE PAIRED POSITIVE: an uninterrupted sweep over the same shape banks every candidate
# exactly once, and a second sweep over the identical (still-landed) roster does not
# double the count — the per-row append preserves exactly the idempotency guarantee the
# single trailing append used to provide.
R14B="$(make_wave_repo r14b)"
N14B=8
i=1
while [ "$i" -le "$N14B" ]; do
  AID14B=$(printf 'ak14b%012x' "$i")
  add_row "$R14B" name="k14b-$i" agent_id="$AID14B" \
    deliverable=".bionic/docs/record/never-$i.md" launched_at="$(iso_ago 600)" \
    tool_use_id="toolu_K14B_$i"
  i=$((i + 1))
done
run_gate "$GATE" "$(stop_payload "$R14B" "$SID" false)"
expect_status "14d: an uninterrupted multi-candidate sweep refuses (all UNMET)" "2" "$RC"
expect_eq "14e: …and banks every candidate exactly once" "$N14B" "$(swept_count "$R14B")"
run_gate "$GATE" "$(stop_payload "$R14B" "$SID" false)"
expect_status "14f: the identical sweep re-run passes — nothing left to verdict" "0" "$RC"
expect_eq "14g: …and the count does not double" "$N14B" "$(swept_count "$R14B")"

# ================================================================= Section 15
section "Section 15: SUPERSESSION — a failed teammate that fixes it gets a second answer (T3, AC-5)"

# THE STATE THIS CLOSES, measured live (record/session-20260815-landing-supervision/
# live-verify.md §B2): the teammate was refused, READ the refusal inside its own sidechain,
# WROTE the promised artifact, and the roster still said `state=UNMET` when the session
# ended. The refusal worked exactly as designed and the record of it was a lie about the
# world — the marker stream carried the failure and never the recovery.
#
# The ruling is SUPERSEDE (plan AC-4, user "Option 1"): the stream records history PLUS
# current state, so nothing is rewritten and a second, later marker says what is true now.
# The Stop sweep is the clock (A-D2), and the arm re-sees teammate rows without disturbing
# the landing arm (A-D5) because it appends a superseding marker, never a sweep verdict.
#
# FIXTURE FIDELITY (declared): the roster rows below are the B2 capture's shape, verbatim in
# every field this arm reads — `intended` then `confirmed`, BOTH carrying `agent_id=` EMPTY
# (teammate mode puts the addressing form in `teammate_id=` and leaves `agent_id=` for the
# identification arm), `teammate_id=<name>@session-<8 hex>` on the confirmed row only. The
# UNMET marker is not hand-written here: every case below DRIVES THE REAL SubagentStop ARM
# to produce it, which is how B2 got its `landing-swept/v1|…|agent_id=alvteam2-…|state=UNMET`
# line — keyed by the transcript-form id off the stopping payload, since no row carried one.
SUP_AID="alvteam2-63ab84a110ebd22f"        # transcript form, B2 verbatim
SUP_ADDR="lvteam2@session-8475b6b6"        # addressing form, B2 verbatim
SUP_BG="[$(bg_teammate t5triyxvo)]"

met_markers()   { swept_lines "$1" | /usr/bin/grep -c 'state=MET'   | tr -d ' '; }
unmet_markers() { swept_lines "$1" | /usr/bin/grep -c 'state=UNMET' | tr -d ' '; }

# ---- the positive: refused, then delivered, then superseded ----
R15="$(make_wave_repo r15)"
add_row "$R15" name=lvteam2 status=intended agent_id= \
  deliverable=.bionic/docs/record/lv-b2-PROBE.txt launched_at="$(iso_ago 600)" \
  tool_use_id=toolu_016TJwSU68bkmhRuBxKFREi4
add_row "$R15" name=lvteam2 status=confirmed agent_id= teammate_id="$SUP_ADDR" \
  deliverable=.bionic/docs/record/lv-b2-PROBE.txt launched_at="$(iso_ago 600)" \
  tool_use_id=toolu_016TJwSU68bkmhRuBxKFREi4
run_gate "$GATE" "$(substop_payload "$R15" "$SID" "$SUP_AID" lvteam2 false "$SUP_BG")"
expect_status "15a: precondition — the teammate lands UNMET and is refused" "2" "$RC"
expect_eq "15a: …with exactly one marker, the failure" "1" "$(swept_count "$R15")"
expect_contains "15a: …recording UNMET" "state=UNMET" "$(swept_lines "$R15")"

# It reads the refusal and writes the file — the exact recovery B2 recorded (sidechain index
# 6, a Write of the promised path, after the injected `Stop hook feedback:` turn).
deliver "$R15" .bionic/docs/record/lv-b2-PROBE.txt
run_gate "$GATE" "$(stop_payload "$R15" "$SID" false)"
expect_status "15b: the next sweep passes — a supersession is not news, and never refuses" "0" "$RC"
expect_empty "15b: …silently" "$OUT_STDERR"
expect_eq "15b: …and appends a SECOND marker beside the first" "2" "$(swept_count "$R15")"
expect_eq "15b: …the failure is still there, unedited (append-only)" "1" "$(unmet_markers "$R15")"
expect_eq "15b: …and the current state is beside it" "1" "$(met_markers "$R15")"
expect_contains "15b: …the OLDER line is the UNMET one — order is chronological" \
  "state=UNMET" "$(swept_lines "$R15" | head -1)"
expect_contains "15b: …and the LATER line is the superseding MET" \
  "state=MET" "$(swept_lines "$R15" | tail -1)"
expect_contains "15b: …keyed by the same agent id the failure was keyed by" \
  "agent_id=$SUP_AID" "$(swept_lines "$R15" | tail -1)"
expect_contains "15b: …and naming the same row" "name=lvteam2" "$(swept_lines "$R15" | tail -1)"

# ---- idempotent: a superseded row is answered, not a standing invitation ----
run_gate "$GATE" "$(stop_payload "$R15" "$SID" false)"
expect_eq "15c: …and writes NO third marker — the latest answer is already MET" \
  "2" "$(swept_count "$R15")"
run_gate "$GATE" "$(stop_payload "$R15" "$SID" false)"
expect_eq "15c: …and no fourth, however many turns end (no marker spam)" "2" "$(swept_count "$R15")"

# ---- the negative: still not delivered, still nothing appended ----
R15D="$(make_wave_repo r15d)"
add_row "$R15D" name=lvteam2 status=intended agent_id= \
  deliverable=.bionic/docs/record/lv-b2-PROBE.txt launched_at="$(iso_ago 600)"
add_row "$R15D" name=lvteam2 status=confirmed agent_id= teammate_id="$SUP_ADDR" \
  deliverable=.bionic/docs/record/lv-b2-PROBE.txt launched_at="$(iso_ago 600)"
run_gate "$GATE" "$(substop_payload "$R15D" "$SID" "$SUP_AID" lvteam2 false "$SUP_BG")"
expect_status "15d: precondition — refused, and the artifact is still absent" "2" "$RC"
run_gate "$GATE" "$(stop_payload "$R15D" "$SID" false)"
expect_status "15d: the sweep passes — the UNMET row is not re-refused by the recheck" "0" "$RC"
expect_empty "15d: …silently, on the same block-once promise (Assumption 27)" "$OUT_STDERR"
expect_eq "15d: …and appends NOTHING: the answer has not changed" "1" "$(swept_count "$R15D")"
expect_eq "15d: …the failure standing alone" "1" "$(unmet_markers "$R15D")"

# ---- NEVER A FIRST VERDICT. A teammate row the SubagentStop arm has not answered for is
# not the sweep's to answer, delivered or not: the sweep cannot tell a working teammate from
# a finished one (its row never leaves background_tasks[], t1 §2.3), so a first verdict here
# is the 2.8-second false refusal Section 13 exists to prevent. The recheck only ever
# SUPERSEDES an answer that already exists.
R15E="$(make_wave_repo r15e)"
add_row "$R15E" name=lvteam2 status=confirmed agent_id= teammate_id="$SUP_ADDR" \
  deliverable=.bionic/docs/record/lv-b2-PROBE.txt launched_at="$(iso_ago 600)"
deliver "$R15E" .bionic/docs/record/lv-b2-PROBE.txt
run_gate "$GATE" "$(stop_payload "$R15E" "$SID" false)"

R15F="$(make_wave_repo r15f)"
add_row "$R15F" name=lvteam2 status=confirmed agent_id= teammate_id="$SUP_ADDR" \
  deliverable=.bionic/docs/record/never.md launched_at="$(iso_ago 600)"
run_gate "$GATE" "$(stop_payload "$R15F" "$SID" false)"

# ---- THE PARTITION HOLDS. An async row is the sweep proper, and its already-swept guard is
# untouched by this arm: once answered it is answered, whatever later appears on disk.
R15G="$(make_wave_repo r15g)"
add_row "$R15G" name=async-one agent_id="$AID_A" \
  deliverable=.bionic/docs/record/never.md launched_at="$(iso_ago 600)"
run_gate "$GATE" "$(stop_payload "$R15G" "$SID" false)"
expect_status "15g: precondition — the async row is swept UNMET and refuses" "2" "$RC"
deliver "$R15G" .bionic/docs/record/never.md
run_gate "$GATE" "$(stop_payload "$R15G" "$SID" false)"
expect_eq "15g: …and the already-swept guard still closes it, once and for all" \
  "1" "$(swept_count "$R15G")"

# ---- THE DISCRIMINATING HALF. 15e and 15f pass against the pre-T3 gate too — they are the
# behaviour that must SURVIVE the change, which makes them silent about whether the guard
# that preserves it is even there. This pair fixes that, on the shape where the difference is
# visible: an ARM3-IDENTIFIED teammate row (`agent_id=` filled, which is what the
# identification arm writes) that has never been marked, with its artifact already on disk.
# The real gate must leave it alone; a copy with the never-a-first-verdict guard removed marks
# it, which is the 2.8-second false verdict the partition exists to prevent.
R15H="$(make_wave_repo r15h)"
add_row "$R15H" name=w2mate agent_id="$TEAM_AID" teammate_id="$TEAM_ADDR" \
  deliverable=.bionic/docs/record/mate.md launched_at="$(iso_ago 600)"
deliver "$R15H" .bionic/docs/record/mate.md
run_gate "$GATE" "$(stop_payload "$R15H" "$SID" false)"
expect_eq "15h: …and marks nothing, delivered or not" "0" "$(swept_count "$R15H")"

SUPDIR="$SANDBOX/hooks-supersede-mutant"
mkdir -p "$SUPDIR"
cp "$HOOKS_DIR/session-sweeper.sh" "$SUPDIR/session-sweeper.sh"
# THE SHIPPED LAYOUT AROUND THE MUTANT: hooks/ beside scripts/lib/, holding THIS
# checkout's library (epic-22 wave-01, N1). Without it the loader's first candidate misses
# and its healing candidates reach the plugin INSTALLED on this machine, whose library is
# whatever was last published — so the mutant would be driven against someone else's
# libraries, and a mutant that fails to load its own fails OPEN and marks nothing, which
# reads here as the guard still holding. Same reason cross-gate's `plant_hook_tree` exists.
mkdir -p "$SANDBOX/scripts/lib"
for _sup_lib in "$HOOKS_DIR/../scripts/lib" "$HOOKS_DIR/../payload/scripts/lib"; do
  if [ -d "$_sup_lib" ]; then cp "$_sup_lib"/*.sh "$SANDBOX/scripts/lib/" 2>/dev/null; break; fi
done
# BOTH guards go, because either one alone still holds the line: an unmarked row has no
# latest state, so the UNMET comparison rejects it too. The mutant is therefore the
# over-broad implementation this arm could plausibly have been written as — supersede any
# teammate row whose artifact is on disk — rather than a single-character typo.
awk '{
       if (index($0, "(nm in mstate)") > 0 || index($0, "mstate[nm] !=") > 0) {
         print "        if (0) continue"
         next
       }
       print
     }' "$GATE" > "$SUPDIR/landing-gate.sh"
expect_eq "15h-mut: the guard PAIR is where the mutation says it is (not vacuous)" \
  "2" "$(diff "$GATE" "$SUPDIR/landing-gate.sh" | /usr/bin/grep -c '^< ' | tr -d ' ')"

R15H_MUT="$(make_wave_repo r15h-mut)"
add_row "$R15H_MUT" name=w2mate agent_id="$TEAM_AID" teammate_id="$TEAM_ADDR" \
  deliverable=.bionic/docs/record/mate.md launched_at="$(iso_ago 600)"
deliver "$R15H_MUT" .bionic/docs/record/mate.md
run_gate "$SUPDIR/landing-gate.sh" "$(stop_payload "$R15H_MUT" "$SID" false)"
expect_eq "15h-mut: with the guard removed the SAME row is marked — the fixture really does discriminate" \
  "1" "$(swept_count "$R15H_MUT")"

# ================================================================= Section 16
section "Section 16: Files: RECONCILIATION — the diff is checked against the declared set (S18, AC-22)"

# --- 16a/16b: THE DISCRIMINATING PAIR — a diff outside Files: refuses, one wholly inside
# does not. Both rows deliver (the deliverable side is MET), so any refusal seen is the
# Files: check speaking, never the contract check above it.
R16A="$(make_git_wave_repo r16a)"
WT16A=$(make_slice_tree "$R16A" slice16a)
commit_files "$WT16A" "in scope" declared/one.sh
commit_files "$WT16A" "out of scope" undeclared/two.sh
add_row "$R16A" name=slice16a agent_id="$AID_A" deliverable=.bionic/docs/record/s16a.md \
  files="declared/" launched_at="$(iso_ago 600)"
deliver "$R16A" .bionic/docs/record/s16a.md
run_gate "$GATE" "$(stop_payload "$R16A" "$SID" false)"
expect_status "16a: a diff outside the declared Files: refuses the stop" "2" "$RC"
expect_contains "16a: …naming the row" "slice16a" "$OUT_STDERR"
expect_contains "16a: …naming the offending file" "undeclared/two.sh" "$OUT_STDERR"
expect_absent "16a: …never the declared file" "declared/one.sh" "$OUT_STDERR"
expect_eq "16a: …the deliverable side stays silent (it WAS delivered)" "0" \
  "$(printf '%s' "$OUT_STDERR" | /usr/bin/grep -c 'LANDING CONTRACT UNMET')"
expect_empty "16a: …the refusal goes to stderr, never stdout" "$OUT_STDOUT"

R16B="$(make_git_wave_repo r16b)"
WT16B=$(make_slice_tree "$R16B" slice16b)
commit_files "$WT16B" "both in scope" declared/one.sh declared/two.sh
add_row "$R16B" name=slice16b agent_id="$AID_A" deliverable=.bionic/docs/record/s16b.md \
  files="declared/" launched_at="$(iso_ago 600)"
deliver "$R16B" .bionic/docs/record/s16b.md
run_gate "$GATE" "$(stop_payload "$R16B" "$SID" false)"
expect_status "16b: a diff wholly inside the declared Files: passes" "0" "$RC"
expect_empty "16b: …silently" "$OUT_STDERR"
expect_eq "16b: …and the row really was processed (marked swept once)" "1" "$(swept_count "$R16B")"

# --- 16c: A Suites:-only brief — no `files=` on the row at all — is not reconciled against
# anything, SILENTLY, no matter what the diff touches: this is the ordinary case for most of
# the fleet today (Files: is the newer of AC-20's two labels), and a stderr line on every
# such landing would turn the routine case into noise on every turn end.
R16C="$(make_git_wave_repo r16c)"
WT16C=$(make_slice_tree "$R16C" slice16c)
commit_files "$WT16C" "anything at all" anywhere/thing.sh
add_row "$R16C" name=slice16c agent_id="$AID_A" deliverable=.bionic/docs/record/s16c.md \
  launched_at="$(iso_ago 600)"
deliver "$R16C" .bionic/docs/record/s16c.md
run_gate "$GATE" "$(stop_payload "$R16C" "$SID" false)"
expect_status "16c: no Files: declared on the row passes" "0" "$RC"
expect_empty "16c: …silently, however wide the diff" "$OUT_STDERR"
expect_eq "16c: …yet the row really was processed (deliverable side still marks it)" \
  "1" "$(swept_count "$R16C")"

# --- 16d: THE CASE-INSENSITIVE FALLBACK. The row name and the worktree's directory basename
# differ only in case (the shape this wave's own dispatch actually produced: row
# `s18-landing-files`, directory `S18-landing-files`) — `worktree_for_row` lowercases and a
# case-sensitive scan would miss it, so this is the one case the farm scan exists for.
R16D="$(make_git_wave_repo r16d)"
git -C "$R16D" worktree add -q "$R16D/.worktrees/Mixed-Case" -b wt/mixedcase >/dev/null 2>&1
git_id "$R16D/.worktrees/Mixed-Case"
commit_files "$R16D/.worktrees/Mixed-Case" "out of scope" undeclared/x.sh
add_row "$R16D" name=mixed-case agent_id="$AID_A" deliverable=.bionic/docs/record/s16d.md \
  files="declared/" launched_at="$(iso_ago 600)"
deliver "$R16D" .bionic/docs/record/s16d.md
run_gate "$GATE" "$(stop_payload "$R16D" "$SID" false)"
expect_status "16d: the worktree is found by name even when the directory case differs" "2" "$RC"
expect_contains "16d: …naming the offending file" "undeclared/x.sh" "$OUT_STDERR"

# --- 16e: A declared Files: with NO locatable worktree (the tree was already removed, or
# never matched by name) is an AMBIGUITY, not a refusal — the same "cannot place it" pass
# every join in this file already takes. The deliverable side still verdicts and marks the
# row, proving the row really was processed rather than skipped for an unrelated reason.
R16E="$(make_git_wave_repo r16e)"
add_row "$R16E" name=ghost-slice agent_id="$AID_A" deliverable=.bionic/docs/record/s16e.md \
  files="declared/" launched_at="$(iso_ago 600)"
deliver "$R16E" .bionic/docs/record/s16e.md
run_gate "$GATE" "$(stop_payload "$R16E" "$SID" false)"
expect_status "16e: a declared Files: with no locatable worktree passes" "0" "$RC"
expect_empty "16e: …silently — an unlocatable tree is ambiguity, not a violation" "$OUT_STDERR"
expect_eq "16e: …yet the row really was processed (deliverable side still marks it)" \
  "1" "$(swept_count "$R16E")"

# --- 16f: "a declared directory covers its files" holds without a trailing slash too.
R16F="$(make_git_wave_repo r16f)"
WT16F=$(make_slice_tree "$R16F" slice16f)
commit_files "$WT16F" "in scope, declared with no trailing slash" declared/one.sh
add_row "$R16F" name=slice16f agent_id="$AID_A" deliverable=.bionic/docs/record/s16f.md \
  files="declared" launched_at="$(iso_ago 600)"
deliver "$R16F" .bionic/docs/record/s16f.md
run_gate "$GATE" "$(stop_payload "$R16F" "$SID" false)"
expect_status "16f: a declared directory with no trailing slash still covers its files" "0" "$RC"
expect_empty "16f: …silently" "$OUT_STDERR"
expect_eq "16f: …and the row really was processed" "1" "$(swept_count "$R16F")"

# --- 16g: an `impact-command:` configured in .bionic/config.yaml — same key S13's dispatch
# wall reads — names the suites the offending files imply, alongside the files themselves.
R16G="$(make_git_wave_repo r16g)"
WT16G=$(make_slice_tree "$R16G" slice16g)
commit_files "$WT16G" "out of scope" undeclared/three.sh
STUB16G="$SANDBOX/impact-stub-16g.sh"
cat > "$STUB16G" <<'STUBEOF'
#!/bin/bash
for f in "$@"; do
  case "$f" in undeclared/*) printf 'fake.test.sh\tstub\n' ;; esac
done
STUBEOF
chmod +x "$STUB16G"
mkdir -p "$R16G/.bionic"
printf 'impact-command: bash %s\n' "$STUB16G" > "$R16G/.bionic/config.yaml"
add_row "$R16G" name=slice16g agent_id="$AID_A" deliverable=.bionic/docs/record/s16g.md \
  files="declared/" launched_at="$(iso_ago 600)"
deliver "$R16G" .bionic/docs/record/s16g.md
run_gate "$GATE" "$(stop_payload "$R16G" "$SID" false)"
expect_status "16g: a diff outside Files: with an impact command configured still refuses" "2" "$RC"
expect_contains "16g: …naming the offending file" "undeclared/three.sh" "$OUT_STDERR"
expect_contains "16g: …and the suite the impact command derived for it" "fake.test.sh" "$OUT_STDERR"

# --- 16h: A DETACHED MAIN CHECKOUT (review-a A-5). `git rev-parse --abbrev-ref HEAD` prints
# the literal string `HEAD` there, and `HEAD` resolves INSIDE the worktree to the worktree's
# own tip — so the merge-base came back non-empty, the diff came back EMPTY, and every
# landing reconciled clean with no refusal and no diagnostic. A wall that is off and quiet
# is indistinguishable from a wall that is passing everything (tests/run.sh:359-364), so the
# inert state is announced. `git bisect`, `git checkout <tag>` and a checkout parked on a
# sha are all ordinary states for this repository during an integration.
R16H="$(make_git_wave_repo r16h)"
WT16H=$(make_slice_tree "$R16H" slice16h)
commit_files "$WT16H" "out of scope" undeclared/four.sh
add_row "$R16H" name=slice16h agent_id="$AID_A" deliverable=.bionic/docs/record/s16h.md \
  files="declared/" launched_at="$(iso_ago 600)"
deliver "$R16H" .bionic/docs/record/s16h.md
git -C "$R16H" checkout -q --detach HEAD
run_gate "$GATE" "$(stop_payload "$R16H" "$SID" false)"
expect_contains "16h: a detached main checkout ANNOUNCES the reconciliation is inert" \
  "the Files: reconciliation is INERT" "$OUT_STDERR"
expect_contains "16h: …naming the reason" "detached HEAD" "$OUT_STDERR"
expect_contains "16h: …naming the row it could not judge" "slice16h" "$OUT_STDERR"
expect_contains "16h: …and the declared set it did not check the diff against" "declared/" "$OUT_STDERR"
expect_eq "16h: …and the row really was processed (deliverable side still marks it)" \
  "1" "$(swept_count "$R16H")"
# CONTROL: the identical fixture in a repo whose main checkout is on its branch — the
# refusal is there, so 16h is about the detached state and not about a fixture that could
# never refuse. A second repo rather than a second run: the sweep marks a row once, so
# re-running the same one proves only that idempotency works.
R16H2="$(make_git_wave_repo r16h2)"
WT16H2=$(make_slice_tree "$R16H2" slice16h2)
commit_files "$WT16H2" "out of scope" undeclared/four.sh
add_row "$R16H2" name=slice16h2 agent_id="$AID_A" deliverable=.bionic/docs/record/s16h2.md \
  files="declared/" launched_at="$(iso_ago 600)"
deliver "$R16H2" .bionic/docs/record/s16h2.md
run_gate "$GATE" "$(stop_payload "$R16H2" "$SID" false)"
expect_absent "16h: control: on a branch the announcement is gone" "reconciliation is INERT" "$OUT_STDERR"
expect_contains "16h: control: …and the diff outside Files: refuses" "undeclared/four.sh" "$OUT_STDERR"

# --- 16i: THE DERIVATION IS BOUNDED (review-c C-17). The impact command costs ~2.6-6.5 s
# and this hook is registered at "timeout": 10 on Stop and SubagentStop, with the call
# inside the per-candidate loop. The budget is spent across the sweep; a row that gets no
# derivation still REFUSES and says the suites were not named. The one thing it must never
# become is a silent pass. NO SEAM: the bound is the shipped 6 seconds, and the stub simply
# outruns it.
R16I="$(make_git_wave_repo r16i)"
WT16I=$(make_slice_tree "$R16I" slice16i)
commit_files "$WT16I" "out of scope" undeclared/slow.sh
STUB16I="$SANDBOX/impact-stub-16i.sh"
printf '#!/bin/bash\nsleep 30\nprintf "never.test.sh\\tstub\\n"\n' > "$STUB16I"
chmod +x "$STUB16I"
mkdir -p "$R16I/.bionic"
printf 'impact-command: bash %s\n' "$STUB16I" > "$R16I/.bionic/config.yaml"
add_row "$R16I" name=slice16i agent_id="$AID_A" deliverable=.bionic/docs/record/s16i.md \
  files="declared/" launched_at="$(iso_ago 600)"
deliver "$R16I" .bionic/docs/record/s16i.md
T16I=$(date +%s)
run_gate "$GATE" "$(stop_payload "$R16I" "$SID" false)"
E16I=$(( $(date +%s) - T16I ))
expect_status "16i: a slow derivation does not turn the refusal into a pass" "2" "$RC"
expect_contains "16i: …the offending file is still named" "undeclared/slow.sh" "$OUT_STDERR"
expect_contains "16i: …and the reader is told the suites were NOT derived" \
  "are NOT named here" "$OUT_STDERR"
expect_absent "16i: …never the answer the command would eventually have given" \
  "never.test.sh" "$OUT_STDERR"
if [ "$E16I" -lt 10 ]; then
  ok "16i: …and the sweep finished inside the hook's own 10s registration (${E16I}s)"
else
  no "16i: …and the sweep finished inside the hook's own 10s registration" "took ${E16I}s"
fi

# --- 16j: `set -f` AROUND THE DIFF-PATH SPLIT (review-a A-11). `$LG_OUTSIDE` comes from
# `git diff --name-only` and was expanded unquoted with no `set -f`, so a committed path
# carrying a glob metacharacter was pathname-expanded against $REPO and the impact command
# was handed files that were never in the diff. The sibling site in
# hooks/dispatch-preflight.sh guards the identical construction. The main checkout below
# holds two files the pattern matches, so an unguarded split has something to expand INTO.
R16J="$(make_git_wave_repo r16j)"
mkdir -p "$R16J/undeclared"
: > "$R16J/undeclared/aX.sh"
: > "$R16J/undeclared/aY.sh"
WT16J=$(make_slice_tree "$R16J" slice16j)
commit_files "$WT16J" "out of scope, with a metacharacter in the name" 'undeclared/a*.sh'
ARGS16J="$SANDBOX/impact-args-16j.txt"
STUB16J="$SANDBOX/impact-stub-16j.sh"
printf '#!/bin/bash\nprintf "%%s\\n" "$@" > %s\nprintf "fake.test.sh\\tstub\\n"\n' "$ARGS16J" > "$STUB16J"
chmod +x "$STUB16J"
mkdir -p "$R16J/.bionic"
printf 'impact-command: bash %s\n' "$STUB16J" > "$R16J/.bionic/config.yaml"
add_row "$R16J" name=slice16j agent_id="$AID_A" deliverable=.bionic/docs/record/s16j.md \
  files="declared/" launched_at="$(iso_ago 600)"
deliver "$R16J" .bionic/docs/record/s16j.md
run_gate "$GATE" "$(stop_payload "$R16J" "$SID" false)"
expect_status "16j: a diff path carrying a glob metacharacter still refuses" "2" "$RC"
expect_eq "16j: …and the impact command received the path from the DIFF, unexpanded" \
  'undeclared/a*.sh' "$(cat "$ARGS16J" 2>/dev/null)"

section "Section 17: the swept-marker extraction fails LOUDLY, or not at all (review-b B-12)"
# tests/lib/swept-marker.sh obtains both the constant and the writer by matching SOURCE TEXT
# of this hook at column 0 — `^SWEPT_SCHEMA=` and `^swept_marker_write()`. Indent the
# function, move the constant, and both `eval`s become no-ops: the builder silently does not
# exist, and the failure surfaces as `command not found` under the runner's stderr-strict
# arm rather than as a named assertion in the suite that depends on it. Seven suites source
# that lib. The framework's own derivation cannot cover it either — `swept_marker_write` is
# not in `_tf_scan`'s token set.
#
# THE MUTANT IS THE REFORMATTING ITSELF, applied to a COPY, with both anchors checked first:
# a doctored hook whose anchors had already moved would prove nothing about the guard.
SM_DIR="$SANDBOX/swept-doctored"
SM_DIR2="$SANDBOX/swept-doctored-const"
SM_DIR3="$SANDBOX/swept-doctored-fn"
mkdir -p "$SM_DIR" "$SM_DIR2" "$SM_DIR3"
# BOTH ANCHORS ONCE, IMMEDIATELY BEFORE THE THREE MUTANTS THEY GUARD — the pair below and
# the two single-line variants further down are the same two rewrites in three
# combinations, so anchoring each pattern once is anchoring all three.
anchor -E "$BIONIC_HOOKS_DIR/landing-gate.sh" '^SWEPT_SCHEMA=' 1
anchor -E "$BIONIC_HOOKS_DIR/landing-gate.sh" '^swept_marker_write\(\)' 1
sed -e 's/^SWEPT_SCHEMA=/  SWEPT_SCHEMA=/' -e 's/^swept_marker_write()/  swept_marker_write()/' \
  "$BIONIC_HOOKS_DIR/landing-gate.sh" > "$SM_DIR/landing-gate.sh"
sed -e 's/^SWEPT_SCHEMA=/  SWEPT_SCHEMA=/' "$BIONIC_HOOKS_DIR/landing-gate.sh" > "$SM_DIR2/landing-gate.sh"
sed -e 's/^swept_marker_write()/  swept_marker_write()/' \
  "$BIONIC_HOOKS_DIR/landing-gate.sh" > "$SM_DIR3/landing-gate.sh"
expect_eq "17a the mutant really did move both anchors" "0" \
  "$(/usr/bin/grep -cE '^(SWEPT_SCHEMA=|swept_marker_write\(\))' "$SM_DIR/landing-gate.sh" | tr -d ' ')"

# A REAL SCRIPT FILE, not `bash -c`: the framework derives a suite's helper calls from its
# own source and refuses a `$0` it cannot read, so a `-c` driver would fail for a reason
# that has nothing to do with the subject.
SM_LIB="$(cd "$(dirname "$0")/lib" && pwd -P)"
SM_DRIVER="$SANDBOX/swept-marker-driver.sh"
cat > "$SM_DRIVER" <<'SMEOF'
#!/bin/bash
set -uo pipefail
SM_LIB_DIR="$1"
BIONIC_HOOKS_DIR="$2"
. "$SM_LIB_DIR/assert.sh"
. "$SM_LIB_DIR/swept-marker.sh"
# THE DRIVER'S OWN EXIT MUST MEAN ONE THING. `type -t` on an undefined name exits 1 all by
# itself, so a driver ending on it would report "the lib refused" for a lib that sourced
# straight through and simply has no builder — the confound this arm exists to tell apart.
echo "SOURCED-ANYWAY"
type -t swept_marker_write || echo "NO-BUILDER"
exit 0
SMEOF
chmod +x "$SM_DRIVER"

SM_OUT=$(bash "$SM_DRIVER" "$SM_LIB" "$SM_DIR" 2>&1)
SM_ST=$?
expect_eq "17b sourcing the lib against a reformatted hook EXITS non-zero" "1" "$SM_ST"
expect_absent "17b …and does not carry on with no builder" "SOURCED-ANYWAY" "$SM_OUT"
expect_contains "17b …naming the lib that could not extract" "tests/lib/swept-marker.sh" "$SM_OUT"
expect_contains "17b …and the hook it read" "landing-gate.sh" "$SM_OUT"

# THE CONSTANT'S HALF, on its own: only the SWEPT_SCHEMA line moved, so the function still
# extracts and the failure has to come from the constant's own check.
SM_OUT2=$(bash "$SM_DRIVER" "$SM_LIB" "$SM_DIR2" 2>&1)
SM_ST2=$?
expect_eq "17c a moved SWEPT_SCHEMA= alone also EXITS non-zero" "1" "$SM_ST2"
expect_contains "17c …naming the constant and the file it was not in" "SWEPT_SCHEMA" "$SM_OUT2"
expect_contains "17c …and the hook it read" "landing-gate.sh" "$SM_OUT2"

# THE FUNCTION'S HALF, on its own: only `swept_marker_write()` is indented, so the constant
# still extracts and the failure has to come from the builder's own presence check — the
# `command not found` this whole guard exists to turn into a named refusal.
SM_OUT4=$(bash "$SM_DRIVER" "$SM_LIB" "$SM_DIR3" 2>&1)
SM_ST4=$?
expect_eq "17e an indented swept_marker_write() alone also EXITS non-zero" "1" "$SM_ST4"
expect_contains "17e …naming the builder that was not extracted" "swept_marker_write" "$SM_OUT4"
expect_absent "17e …and never reaches the code that would have called it" "SOURCED-ANYWAY" "$SM_OUT4"

# CONTROL: the SHIPPED hook, same three lines — it sources clean and the builder is real.
SM_OUT3=$(bash "$SM_DRIVER" "$SM_LIB" "$BIONIC_HOOKS_DIR" 2>&1)
SM_ST3=$?
expect_eq "17d control: against the shipped hook the lib sources clean" "0" "$SM_ST3"
expect_contains "17d …and the builder is a real function" "function" "$SM_OUT3"

finish
