#!/bin/bash
# THE LANDING SWEEP — epic-16 wave-01 (the gate), wave-03 slice T4c (the sweep).
#
# Stop. On every orchestrator turn end, during an active wave: read this session's roster,
# take a landing verdict for every contract that has LANDED since the last sweep, and refuse
# the stop once if any of them named artifacts that are not on disk. Outside an active wave,
# or on any ambiguity along the way, the stop passes through untouched.
#
# WHY A SWEEP, AND WHY ON THIS EVENT. Until wave-03 this ran on the subagent's own stop and
# judged the one agent that stopped. That event cannot reach it any more, and not by
# accident: skill-frontmatter hooks live in the harness's `appState.sessionHooks`, keyed by
# SESSION id, and the subagent-stop path looks them up under `agentId ?? session.id` — the
# subagent's id, which has no entry. Every event dispatched in a subagent context is
# therefore structurally invisible to a skill-registered hook, so a wall registered there is
# installed, syntactically fine, green in its own suite, and never runs
# (record/session-20260814-wave-detector-terminal-state/t4b-probe-report.md §3, read out of
# the shipped binary and confirmed by an eleven-session dual-channel A/B).
#
# `Stop` is delivered to that channel, fires once per orchestrator turn, keeps firing on
# turns the skill was not re-invoked on — and, the fact that makes the latency a non-issue,
# is GENERATED BY a background agent's landing: the completion wakes a fresh turn, which
# closes 2.5–3.7 s later and delivers a Stop nobody asked for (§2.3, §4, two independent
# replications). So a sweep here runs both when the orchestrator pauses and shortly after
# each landing, which is exactly the two moments a landing contract cares about.
#
# HOW A LANDING IS RECOGNISED. The payload carries `background_tasks[]`, one row per
# subagent that is STILL RUNNING, keyed by the same `id` the roster's `agent_id=` holds —
# `tool_response.agentId` at dispatch, `agent_id` on SubagentStart, `background_tasks[].id`
# here, one string across all three (§2.2, §4, measured on one dispatch). A roster row whose
# id is ABSENT from that list has landed; a row still on it is skipped in silence. Nothing
# on this path reads `agent_type`, which carries the subagent TYPE and never the dispatch
# name — the join defect t4-probes-report.md §5.1 found open and this slice closes.
#
# ONCE PER ROW, EVER. Stop fires every turn and a landed row stays landed, so a sweep that
# re-verdicted would refuse every turn end for the rest of the session over one agent's
# failure — the false-alarm shape this machinery exists to end. Each verdicted row is
# journalled as a `landing-swept/v1|` line in the roster file it belongs to. That is the one
# thing this script writes, and it rides IN the roster because the promise it keeps must not
# outlive the rows it is about. Inertness to the rest of the fleet is NOT a blanket property
# of every roster reader — it holds per reader, for one of two separate reasons, and both
# must be true or the marker leaks into a reader's answer (t6-review.md F-1, reproduced live:
# `hooks/session-poker.sh` read the roster with no schema filter and the marker silenced its
# overdue NOTIFY for the swept row). `hooks/execution-recorder.sh`, `hooks/session-sweeper.sh`,
# `hooks/stop-guard.sh`, `hooks/stop-check.sh` and `hooks/stop-orders.sh` filter on the
# `roster-state/v1|` prefix before reading a row, so the marker's `landing-swept/v1|` prefix
# never matches. `hooks/dispatch-preflight.sh` does NOT filter on that prefix and is immune
# only by accident: its `owning_row_for` skips any row with no `deliverable=`, a field the
# marker never carries. That second immunity is undeclared to its own reader and untested —
# one added field to the marker's schema would turn it into a second instance of this bug.
#
# IT OWNS NO PREDICATE. The question "did this contract land" is answered by
# `hooks/session-sweeper.sh verdict <name>`, and this script parses that verb's machine line
# for `state=`, `acked=` and `detail=`. It never stats a deliverable and never forms an
# opinion about staleness, waivers or liveness-by-progress. It reads exactly two fields of
# the roster for itself — `agent_id`, which is the join key above, and `name`, which is what
# the verb must be asked about — plus `deliverable` as a pure PREFILTER: a row declaring
# nothing is MET vacuously by the verb's own rule, so skipping it cannot change an answer,
# only the cost of getting one.
#
# THE SECOND ARM: TEAMMATES LAND AT SubagentStop (session-20260815, T2; design D2).
# Everything above is true of an async subagent and false of a named teammate. A teammate
# carries THREE id namespaces that do not join — the addressing form at dispatch
# (`mate@session-7b7a693c`), the transcript form on SubagentStart/Stop
# (`amate-fdaa80c4b3cb703f`), and an opaque nine-character token in `background_tasks[]` that
# appears in no dispatch-time payload at all — and its row NEVER LEAVES that array: measured
# `status:"running"` on the last Stop of the session, 2 m 41 s after the teammate had
# delivered its own SubagentStop (t1-probe-report.md §2.1–§2.3, CLI 2.1.233). So the sweep
# predicate is not merely unjoinable for teammates, it is wrong in both directions: today
# every teammate row is skipped for want of an id, and the moment a writer fills one, every
# teammate reads as LANDED 2.8 s after dispatch, while it is still working.
#
# `SubagentStop` is the transition itself rather than a reconstruction of it, and it carries
# the id, the name and the moment in one payload. This arm therefore takes the SAME verdict
# from the SAME verb, writes the SAME marker through the SAME append, and speaks the SAME
# refusal — what differs is only which row is judged and when. It reads no live set (the
# stopping teammate is still in it), joins by `agent_id` first and by `agent_type` — which
# carries the dispatch NAME for a teammate — second, and both joins are scoped to rows
# carrying a non-empty `teammate_id=`.
#
# THAT SCOPE CUTS BOTH WAYS, and the sweep half of it is in the fold below: teammate rows are
# skipped there, with the one exception the next paragraph names. An async subagent stopping on this event is passed over in silence, because
# the sweep is the arm that owns it and the marker written here is exactly what would tell
# the sweep the row is already answered for — verdicting an async row here would not
# duplicate the sweep, it would silently replace the refusal the orchestrator sees with one
# delivered somewhere else.
#
# THE SUPERSESSION RECHECK (session-20260815-landing-cleanup, T3; ruling: supersede). The one
# thing the sweep does with a teammate row, and it is not a verdict. A refused teammate is
# told inside its own sidechain at the one moment it can still act, and it acts: measured
# live, the teammate read the feedback, wrote the promised artifact, and the roster still read
# `state=UNMET` when the session ended (record/session-20260815-landing-supervision/
# live-verify.md §B2). The refusal was correct and its record was a false statement about the
# world. So on any later Stop, a teammate row whose LATEST marker says UNMET and whose
# deliverable the verb now finds gets a SECOND marker appended, saying MET. Both persist, in
# order: the stream is history plus current state, and nothing is ever rewritten. It never
# refuses, it never writes a FIRST verdict for a teammate (an unmarked row stays the
# SubagentStop arm's, delivered or not), it costs nothing once the answer is MET, and it needs
# no clock of its own — Stop already fires on every turn end and shortly after every landing.
#
# WHERE THE REFUSAL GOES, stated because it differs from the sweep and the difference is not
# ours to change: a blocking Stop-hook exit on the main thread reaches the orchestrator,
# while on SubagentStop the harness delivers the feedback TO THE SUBAGENT and lets it
# continue so it can act on it (read out of the shipped CLI 2.1.233 binary:
# "additionalContext is non-error feedback delivered to the subagent; the subagent continues
# so it can act on it", beside the block-cap guidance "For Stop/SubagentStop hooks, check
# stop_hook_active in the input and return success while it is true"). So the agent that
# broke its contract is the one told about it, at the one moment it can still fix it, and the
# orchestrator-facing record is the roster marker plus the poker overdue NOTIFY that reads
# the same rows. `stop_hook_active` is honoured here for the reason the binary gives.
#
# FAIL DIRECTIONS (pinned by tests/landing-gate.test.sh):
#   - not a Stop or SubagentStop payload                 -> pass, silent (relevance hoist)
#   - SubagentStop with no agent_id, or one carrying
#     field separators                                   -> pass, silent
#   - SubagentStop matching no teammate row (a phantom
#     harness agent, or an async subagent the sweep
#     owns)                                              -> pass, silent
#   - no `background_tasks` key: nothing to tell landed
#     from live                                          -> pass, silent (ambiguity)
#   - stop_hook_active true                              -> pass, silent (blocks ONCE)
#   - cwd/repo unresolvable, or no session_id, or a
#     session_id that is not shaped like one             -> pass, silent (ambiguity)
#   - no roster for this session, or a symlinked one     -> pass, silent
#   - no active wave                                     -> pass, silent
#   - the sweeper is absent                              -> pass, silent
#   - a row with an EMPTY agent_id: it cannot be placed
#     on either side of the landed/live line             -> skip, unmarked (ambiguity)
#   - the verdict exits anything but 0 or 1, or prints
#     no line at all                                     -> skip, UNMARKED (no answer, so
#                                                          the row is still owed one)
#   - the verdict says anything but UNMET, or says UNMET
#     over an acked row                                  -> mark swept, pass
#   - the verdict says UNMET on a landed row             -> REFUSE, quoting its detail
#   - a swept teammate row, latest marker UNMET, and the
#     verdict now says MET                               -> append a superseding marker, pass
#   - the same row, verdict still anything but MET       -> nothing appended, pass, silent
#   - a teammate row with NO marker at all               -> skip, unmarked (never a first
#                                                          verdict from this event)
#
# THE Files: RECONCILIATION (S18, AC-22) rides the same per-candidate loop, once per row, on
# a "verdict" candidate only — a recheck never speaks (belt-on-belt with "supersession never
# speaks" above) and a row with no `deliverable=` never becomes a candidate at all, so it is
# out of reach of this check too, on the same "declares nothing" reasoning the deliverable
# checks already use:
#   - the row's `files=` is empty (a Suites:-only brief,
#     or a row that predates the wall)                    -> not reconciled, silent, pass
#   - the row's worktree cannot be located or is gone,
#     or its branch has no merge-base with the main
#     checkout's current branch                            -> not reconciled, silent (ambiguity)
#   - the diff has no path outside the declared `files=`   -> pass, silent
#   - the diff touches a path outside the declared
#     `files=`                                              -> REFUSE, naming the file(s) and
#                                                          (impact-command configured) the
#                                                          suites `impact` derives for them
#
# Exit code 2 = block the stop in Claude Code hooks; stderr goes back to the orchestrator,
# which is why the refusal must name the row and its artifacts rather than the rule.
# [WALL: tests/landing-gate.test.sh]
#
# Registered on both channels: hooks/hooks.json (agent contexts, behind agent-context-guard.sh) and skills/canonical-sdlc/SKILL.md frontmatter (main thread).

set -uo pipefail

SWEPT_SCHEMA="landing-swept/v1"
# Reader copy of hooks/dispatch-preflight.sh's roster constant, on the same precedent
# hooks/session-sweeper.sh states for its copy: a prefix drift here is a mislabeled scan.
ROSTER_VERSION="v1"

# THE ONE WRITER (S15, AC-26; research-code-map §2.c). Defined here, not sourced from a
# shared lib file: this hook's own `BIONIC_LIB_WANT` stays "root.sh run.sh session.sh"
# unchanged, and a copy of this file (as tests/landing-gate.test.sh's own mutation-arm
# fixtures make) carries the writer with it rather than depending on a lib file resolving
# through the loader's registry/cache fallback to whatever was last landed there.
# hooks/session-poker.sh's `adopt_copy_marker` never calls this function — its job is to
# relay a line this one already wrote, verbatim — but it DOES share the `SWEPT_SCHEMA`
# constant above, spelled identically (byte-pinned, tests/cross-gate-agreement.test.sh),
# never as a second literal the way `grep -rn SWEPT_SCHEMA hooks/*.sh` could miss.
swept_marker_write() {  # <roster file> <at> <session> <name> <agent id> <state> -> 0/1
  local f="$1" at="$2" sid="$3" name="$4" aid="$5" state="$6"
  [ -n "$f" ] || return 1
  printf '%s|at=%s|session=%s|name=%s|agent_id=%s|state=%s\n' \
    "$SWEPT_SCHEMA" "$at" "$sid" "$name" "$aid" "$state" >> "$f" 2>/dev/null
  return 0
}

# ---------------------------------------------------------- FILES: RECONCILIATION (S18, AC-22)
#
# DECLARE -> DERIVE -> RECONCILE (design ledger D2). `hooks/dispatch-preflight.sh` derives a
# BUDGET from a brief's `Files:` at dispatch; these two functions are the third leg — asking,
# once a row is landed, whether the diff the agent actually produced stayed inside that same
# declared set. Called from the per-candidate loop below, never from the sweeper: the
# sweeper answers about the DELIVERABLE, this answers about the DIFF, and the two questions
# share a candidate line but not a verdict.

# The row's worktree, by the ONE mapping the fleet has for "which tree belongs to whom"
# (payload/scripts/lib/worktree.sh's `worktree_for_row`, sourced above as `BIONIC_LIB_WANT`
# declares). That function only builds a path string — it lowercases the row name and never
# stats anything — which a case-INSENSITIVE filesystem (macOS, this wave's covered
# environment) resolves against a mixed-case directory for free. A case-SENSITIVE one
# (Linux, fog) would not, so the fallback below scans the farm by lowercased basename before
# giving up; it is the one place this file re-derives any part of the mapping, and it does
# so only to absorb a filesystem property `worktree_for_row` does not, never to re-decide
# which directory a row's name means.
_lg_worktree_for_name() {  # <repo> <row name> -> abs worktree path on stdout, or nothing
  local repo="$1" name="$2" cand d base lc
  if declare -f worktree_for_row >/dev/null 2>&1; then
    cand=$(worktree_for_row "$repo" "$name" 2>/dev/null)
    if [ -n "$cand" ] && [ -d "$cand" ]; then printf '%s' "$cand"; return 0; fi
  fi
  lc=$(printf '%s' "${name#W-}" | tr '[:upper:]' '[:lower:]')
  [ -n "$lc" ] && [ -d "$repo/.worktrees" ] || return 1
  for d in "$repo"/.worktrees/*/; do
    [ -d "$d" ] || continue
    base=$(basename "$d")
    if [ "$(printf '%s' "$base" | tr '[:upper:]' '[:lower:]')" = "$lc" ]; then
      printf '%s' "${d%/}"
      return 0
    fi
  done
  return 1
}

# Is a path the diff touched inside the declared set? Exact match, or under a declared
# DIRECTORY — "a declared directory covers its files" (S18 brief) — checked without caring
# whether the author spelled the directory with a trailing slash.
_lg_path_declared() {  # <diff path> <comma-joined declared files>
  local p="$1" list="$2" old_ifs entry
  old_ifs="$IFS"; IFS=','; set -f
  # shellcheck disable=SC2086
  set -- $list
  set +f; IFS="$old_ifs"
  for entry in "$@"; do
    entry="${entry%/}"
    [ -n "$entry" ] || continue
    [ "$p" = "$entry" ] && return 0
    case "$p" in "$entry"/*) return 0 ;; esac
  done
  return 1
}

INPUT=$(cat)
_jq() { printf '%s' "$INPUT" | jq -r "$1 // empty" 2>/dev/null; }

# ---------- relevance first: the cheapest checks, before any git resolution ----------

# TWO EVENTS, TWO ARMS, ONE ROSTER SPLIT BETWEEN THEM. `Stop` is the sweep (below);
# `SubagentStop` is the teammate landing verdict, and it arrives on the settings channel
# behind hooks/agent-context-guard.sh because no subagent-context event reaches the skill
# frontmatter at all. An absent field is not treated as a mismatch, so a hand-run payload
# still sweeps.
EVENT=$(_jq '.hook_event_name')
case "$EVENT" in
  ""|Stop)      MODE=sweep ;;
  SubagentStop) MODE=landing ;;
  *)            exit 0 ;;
esac

# Read on BOTH paths, so neither is a variable bound on only some of them (`set -u`), and
# read here rather than at the join so the shape checks sit beside every other one.
STOP_AGENT_ID=""
STOP_AGENT_NAME=""
LIVE_IDS=""

if [ "$MODE" = "sweep" ]; then
  # THE LIVE SET, and the whole of the landed/live discrimination. Its ABSENCE is not an empty
  # set: an empty array means every dispatch has finished (the payload says so on every turn
  # where nothing is running), while a missing key means this is not a payload that can tell
  # us, and judging on it would hold running agents to contracts they are still working on.
  [ "$(printf '%s' "$INPUT" | jq -r 'if has("background_tasks") then "yes" else empty end' 2>/dev/null)" = "yes" ] || exit 0
  LIVE_IDS="|$(printf '%s' "$INPUT" \
    | jq -r '[.background_tasks[]?.id // empty] | join("|")' 2>/dev/null | tr -d '\n')|"
else
  # THE LANDING ARM READS NO LIVE SET, and that is the point of it rather than an omission.
  # This payload carries `background_tasks[]` too, and the stopping teammate is STILL IN IT —
  # measured `status:"running"` on the last Stop of the session, 2 m 41 s after its own
  # SubagentStop, because an in-process teammate stays addressable until the session ends
  # (t1-probe-report.md §2.3). Landing-by-disappearance is a subagent-only signal; here the
  # EVENT is the landing, delivered with the id, the name and the moment in one payload.
  STOP_AGENT_ID=$(_jq '.agent_id')
  [ -n "$STOP_AGENT_ID" ] || exit 0
  # SHAPE-CHECKED BEFORE IT BECOMES A FIELD, on the same reasoning the session key gets: this
  # value is written into a `landing-swept/v1|…|agent_id=` marker line, and a `|` or a newline
  # in it would forge a field or a whole row on the roster. The transcript form is
  # `a<name>-<16 hex>` and names are alphanumeric, so this silences nothing real.
  case "$STOP_AGENT_ID" in *[!A-Za-z0-9_.@-]*) exit 0 ;; esac
  # The NAME, for the fallback join, and only if it is shaped like one. `agent_type` carries
  # the dispatch name for a teammate and the subagent type for an async dispatch (t1 §2.1);
  # the harness's own phantom agents send it empty. An unusable value drops the fallback
  # rather than the whole arm — the id join above may still place the row.
  STOP_AGENT_NAME=$(_jq '.agent_type')
  case "$STOP_AGENT_NAME" in *[!A-Za-z0-9_-]*) STOP_AGENT_NAME="" ;; esac
fi

# BLOCKS ONCE, and this is the whole mechanism. Claude Code re-enters the stop with
# stop_hook_active true after a hook blocked it; refusing again would wedge the turn in a
# loop it has no way out of. One refusal names the contracts; the second stop is the
# orchestrator's to decide about. (jq's `//` folds `false` to empty, so a literal "true" is
# the only value that can match here — which is the comparison we want anyway.) Nothing is
# verdicted on a re-entry either: the rows are still owed their one answer.
[ "$(_jq '.stop_hook_active')" = "true" ] && exit 0

# ---------- ambiguity: cannot locate the repo or the session -> pass, silent ----------
CWD=$(_jq '.cwd')
[ -n "$CWD" ] || exit 0
# ---------- the library ----------
#
# One loader idiom, byte-identical in every hook (spec AC-16); its source of truth is
# payload/scripts/lib/loader.sh. FAIL OPEN: the landing verdict is advisory or repeatable, and a
# hook that refused because a file was missing would hold every turn in every session
# on the machine hostage to it.
BIONIC_LIB_WANT="root.sh run.sh session.sh worktree.sh"
# --- bionic-loader/v2 BEGIN
# Find the bionic library. This text is pasted BYTE-IDENTICALLY into every hook; a
# library cannot load itself, so the duplication is the design and
# tests/cross-gate-agreement.test.sh pins every copy against `bionic_loader_pin` in
# payload/scripts/lib/loader.sh. Behaviour: tests/loader.test.sh.
#
# CONTRACT. Set BIONIC_LIB_WANT to the space-separated basenames this hook sources,
# on a line above this block. Afterwards exactly one of these is non-empty:
#   BIONIC_LIB          a readable directory holding every wanted basename
#   BIONIC_LIB_MISSING  the library this hook wanted and did not get
# BIONIC_LIB_CANDS always lists, in order, every location that was tried.
#
# CANDIDATES. Later classes are evaluated only after the earlier ones fail, so a
# healthy hook pays nothing for the healing path — not a jq, not a registry read.
#  (1) beside the hook. TWO SPELLINGS OF ONE DIRECTORY, because the shipped tree has
#      two real shapes: the installed plugin root, where hooks/ and scripts/ are
#      siblings, and the repo, where payload/hooks is a symlink to the top-level
#      hooks/ and the library lives under payload/scripts/lib. "$0" is textual and
#      `..` is resolved by the kernel AFTER the symlink, so the first spelling alone
#      would find nothing in a directory-source session.
#  (2) the marketplace SOURCE TREE. installed_plugins.json names the marketplace this
#      plugin was installed from; that marketplace's source.path in
#      known_marketplaces.json is the tree. The marketplace is read, never assumed:
#      a fork installs under its own name.
#  (3) the newest version directory in that marketplace's plugin cache, by
#      THREE-INTEGER compare — 1.10.0 beats 1.3.2, which a lexical sort gets backwards.
# (2) and (3) heal a partial breakage: one location damaged, a sibling intact. An
# upstream-broken publish breaks every location equally and is not covered.
#
# TESTS OVERRIDE THE MACHINE, never the reverse. BIONIC_PLUGINS_DIR (default
# "$HOME/.claude/plugins") is the only door to the registry and the cache.
BIONIC_LIB=""; BIONIC_LIB_MISSING=""; BIONIC_LIB_CANDS=""
_bl_dir="$(dirname "$0")"
_bl_want="${BIONIC_LIB_WANT:-}"
_bl_try() {
  [ -n "${1:-}" ] || return 1
  if [ -z "$BIONIC_LIB_CANDS" ]; then BIONIC_LIB_CANDS="$1"; else BIONIC_LIB_CANDS="$BIONIC_LIB_CANDS, $1"; fi
  [ -d "$1" ] || return 1
  for _bl_f in $_bl_want; do [ -r "$1/$_bl_f" ] || return 1; done
  BIONIC_LIB="$1"
}
if ! _bl_try "$_bl_dir/../scripts/lib" && ! _bl_try "$_bl_dir/../payload/scripts/lib"; then
  _bl_pd="${BIONIC_PLUGINS_DIR:-${HOME:-/nonexistent}/.claude/plugins}"
  _bl_mk=""
  if [ -r "$_bl_pd/installed_plugins.json" ]; then
    # First key only, and the prefix stripped by parameter expansion rather than
    # `sed | head`: the block's only external commands are `dirname` and `jq`, and
    # `jq` runs with its stderr closed, so a machine missing jq degrades to
    # BIONIC_LIB_MISSING in silence instead of printing a shell diagnostic.
    _bl_keys="$(jq -r '(.plugins // {}) | keys[] | select(startswith("bionic@"))' "$_bl_pd/installed_plugins.json" 2>/dev/null)"
    _bl_mk="${_bl_keys%%
*}"
    _bl_mk="${_bl_mk#bionic@}"
  fi
  if [ -n "$_bl_mk" ]; then
    _bl_src=""
    if [ -r "$_bl_pd/known_marketplaces.json" ]; then
      _bl_src="$(jq -r --arg mk "$_bl_mk" '.[$mk].source.path // empty' "$_bl_pd/known_marketplaces.json" 2>/dev/null)"
    fi
    if [ -n "$_bl_src" ]; then _bl_try "$_bl_src/payload/scripts/lib" || :; fi
    if [ -z "$BIONIC_LIB" ]; then
      _bl_best=""; _bl_bestk=""
      for _bl_v in "$_bl_pd/cache/$_bl_mk/bionic"/*; do
        [ -d "$_bl_v" ] || continue
        _bl_n="${_bl_v##*/}"
        case "$_bl_n" in ''|*[!0-9.]*) continue ;; esac
        _bl_x1=""; _bl_x2=""; _bl_x3=""
        IFS=. read -r _bl_x1 _bl_x2 _bl_x3 _bl_rest <<BIONIC_LOADER_VER
$_bl_n
BIONIC_LOADER_VER
        _bl_k="$(printf '%05d%05d%05d' "$((10#${_bl_x1:-0}))" "$((10#${_bl_x2:-0}))" "$((10#${_bl_x3:-0}))" 2>/dev/null)" || continue
        if [ -z "$_bl_bestk" ] || [ "$_bl_k" \> "$_bl_bestk" ]; then _bl_bestk="$_bl_k"; _bl_best="$_bl_n"; fi
      done
      if [ -n "$_bl_best" ]; then _bl_try "$_bl_pd/cache/$_bl_mk/bionic/$_bl_best/scripts/lib" || :; fi
    fi
  fi
fi
if [ -z "$BIONIC_LIB" ]; then
  # The name in the message is the first library this hook asked for. A candidate
  # directory qualifies only when it holds ALL of them, so with none qualifying the
  # first wanted name is the honest thing to hand the reader.
  BIONIC_LIB_MISSING="${_bl_want%% *}"
  [ -n "$BIONIC_LIB_MISSING" ] || BIONIC_LIB_MISSING="scripts/lib"
fi
# FAIL OPEN — for every hook whose work is advisory or reversible. One line, then
# stand aside. Blocking reversible work because a file is missing buys no safety and
# costs the session.
loader_fail_open() {
  echo "$1: library ${BIONIC_LIB_MISSING:-the bionic library} not found at ${BIONIC_LIB_CANDS:-(no candidate)} — hook stepping aside; run /bionic:doctor" >&2
  exit 0
}
# FAIL CLOSED — for a wall over an irreversible action. Refuse, but never lock the
# user out of the repair: four commands are permitted by WHOLE-STRING match, checked
# here, before the hook sources anything. Whole-string and not prefix, so
# `claude plugin update bionic@bionic; git push origin main` is refused like any
# other push. There is no env-var override: a variable an agent turn can set on
# itself is not a wall.
loader_fail_closed() {
  _bl_root="$(cd "$(dirname "$0")/.." 2>/dev/null && pwd -P)" || _bl_root=""
  [ -n "$_bl_root" ] || _bl_root="$(dirname "$0")/.."
  case "${2:-}" in
    "claude plugin update bionic@bionic"|\
    "claude plugin install bionic@bionic"|\
    "bash $_bl_root/scripts/doctor.sh"|\
    "bash $_bl_root/scripts/setup.sh") exit 0 ;;
  esac
  cat >&2 <<BIONIC_LOADER_REFUSE
BLOCKED: $1 cannot load its library (${BIONIC_LIB_MISSING:-the bionic library}), so it
cannot read this command. A wall that cannot read a command refuses it rather than
waving it through.

Looked in: ${BIONIC_LIB_CANDS:-(no candidate)}

Until the plugin is whole again this wall permits exactly four commands, each matched
as a whole string:

    claude plugin update bionic@bionic
    claude plugin install bionic@bionic
    bash $_bl_root/scripts/doctor.sh
    bash $_bl_root/scripts/setup.sh

Anything else is refused, including one of those four with another command chained
after it. Run one of them, or act from your own terminal.
BIONIC_LOADER_REFUSE
  exit 2
}
# --- bionic-loader/v2 END
if [ -n "$BIONIC_LIB_MISSING" ]; then loader_fail_open "landing-gate"; fi
# shellcheck source=/dev/null
. "$BIONIC_LIB/root.sh"
# shellcheck source=/dev/null
. "$BIONIC_LIB/run.sh"
# shellcheck source=/dev/null
. "$BIONIC_LIB/session.sh"
# THE ROW -> WORKTREE MAPPING (S18, AC-22). `worktree_for_row` is the one place that
# convention lives (payload/scripts/lib/worktree.sh: "a second spelling of it there is a
# second definition of which tree belongs to whom") — sourced here so the Files:
# reconciliation below asks it rather than re-deriving the mapping.
# shellcheck source=/dev/null
. "$BIONIC_LIB/worktree.sh"

# THE ROOT (spec AC-10, lib/root.sh). `git rev-parse --show-toplevel` answered with the
# WORKTREE's own root, so a stop raised from a linked worktree looked for the roster
# under a tree the dispatch wall had never written one into — and this gate then passed
# every row in silence, exactly where a wave most needs it. `project_root` maps a linked
# worktree onto its main repository and walks for the nearest real `.bionic`, so the
# reader and the writer land on one address space.
REPO=$(project_root "$CWD")
[ -n "$REPO" ] && [ -d "$REPO" ] || exit 0

# THE SESSION KEY, from the library (design §1, R-1): the ENVIRONMENT value is primary and
# the payload is a witness. This file used to prefer the payload on the reasoning that a
# hook process's env is not a documented carrier of the id — measurement overtook that
# (A-probe-1/A-probe-2: a plain /clear re-keys the env, the payload and the pid file
# together, and hook processes see the new value). What made the choice matter is that
# the roster filename is built from it and other readers took the env: two spellings of
# one session produced two rosters. It is passed to the sweeper below for the same reason.
SID=$(session_id "$(_jq '.session_id')" 2>/dev/null) || SID=""
[ -n "$SID" ] || exit 0
# SHAPE-CHECKED BEFORE IT BECOMES A PATH, exactly as hooks/dispatch-preflight.sh checks it.
# This value is interpolated into `roster-${SID}.state` below — a file this script now
# APPENDS to — and exported to the sweeper, which builds its own ledger and findings paths
# from it; the symlink guards on those paths check the state directory and the exact
# filenames, so a key carrying separators does not trip a guard, it leaves the directory the
# guards protect. Session ids are harness-minted UUIDs today and nothing reaches this, but
# every other payload value on this path is sanitized and this one was not (Step-6 S-4).
case "$SID" in *[!A-Za-z0-9_-]*) exit 0 ;; esac

# ---------- THE ENGAGEMENT SWITCH — asked before anything else ----------
#
# task-engaged-session: bionic's walls are the RUN's, not the repo's, and a run is entered
# by invoking canonical-sdlc. A session that never did is a bystander here and must not see
# a refusal, an advisory, or a state write from this hook. `engaged_session` (lib/run.sh) is
# true only for a REGULAR file at `.bionic/tmp/engaged-<sid>.state`; every unreadable state —
# absent, symlink, foreign sid, `unknown` — reads as NOT engaged. Silent, exit 0: the
# direction §7 gives every start-side ambiguity, and here it is the consent boundary itself
# (1.3.2 close-out ruling — the arming partition IS the consent boundary).
engaged_session "$REPO" "$SID" || exit 0

ROSTER_FILE="$REPO/.bionic/tmp/roster-${SID}.state"
# Existence first, so a session that has dispatched nothing costs one stat. The symlink
# guard is the write half of TDD §8: a repo controls its own .bionic/, and a link at any
# level redirects this script's marker append outside the repo.
[ -e "$ROSTER_FILE" ] || exit 0
[ -L "$REPO/.bionic" ] && exit 0
[ -L "$REPO/.bionic/tmp" ] && exit 0
[ -L "$ROSTER_FILE" ] && exit 0

# ---------- THE RUN PREDICATE IS GONE — ENGAGEMENT SCOPES THIS HOOK (task-engaged-session) --
#
# It used to take the run predicate here — `PLAN=$(active_run <repo>)`, exit 0 on false —
# and nothing below ever consulted
# the value: the contract this gate enforces is a roster row this
# session's own dispatch wall wrote, and the verdict is hooks/session-sweeper.sh's.
# The plan answered WHETHER, which is now engagement's question and is answered above.
#
# WHY THIS HOOK MOVES WITH THE DISPATCH WALL RATHER THAN KEEPING A RUN GATE. The four
# members of the roster lifecycle — hooks/dispatch-preflight.sh writes an `intended` row,
# this family confirms it, the landing gate takes its verdict, the stop gate polices the
# stop — have to share one scope or the lifecycle splits: the dispatch wall runs for an
# engaged session with no plan yet (AC-23, a fresh run's Step 0 precedes its plan), and a
# recorder or a gate that stayed silent for want of a plan would leave rows nothing ever
# answers for. A landing contract also OUTLIVES the run that created it — engagement does
# not end when `current:` reaches 9 (plan §Lifecycle) — and a verdict owed on an agent this
# session launched is owed after the run closes too.

# ---------- this session is engaged: sweep ----------

# The sweeper is this script's SIBLING — the payload ships every hooks/*.sh in one
# directory, so the same resolution holds in the repo and under the mounted plugin's
# hooks/ that hooks/hooks.json roots at ${CLAUDE_PLUGIN_ROOT}. No PATH
# lookup (a hook's PATH is not ours to trust) and no environment override (a seam on the
# path under test would leave the production path unverified).
SWEEPER="$(cd "$(dirname "$0")" 2>/dev/null && pwd)/session-sweeper.sh"
[ -f "$SWEEPER" ] || exit 0

# ONE PASS OVER THE ROSTER, and it is the only cost this script pays on a turn where nothing
# landed. The fold rule is hooks/session-sweeper.sh's own (`latest_rows`), because the verb
# is what will be asked and a reader that folded differently would ask about a row the verb
# never answers for: rows of THIS session only, keyed by name, FIRST field of a key wins
# within a row, latest row wins across them, an empty name folds to `(unnamed)`.
#
# `agent_id` is taken from the latest row that CARRIES one rather than from the latest row
# outright. The field starts empty on the `intended` row the dispatch wall writes and is
# filled by hooks/execution-recorder.sh at confirmation; it never goes back to empty, so
# this is monotone rather than a preference, and it keeps a row joinable if a future writer
# ever appends without copying it forward.
#
# The output is TAB-delimited `<agent_id> <name> <kind>`, one line per unswept, joinable,
# contract-bearing row. A tab cannot appear inside a field — every writer on this roster runs
# its values through a sanitizer that turns one into a space — and the name is folded the
# same way the verb folds it. `kind` is `verdict` for a row being answered for the first (and
# only) time, and `recheck` for the supersession arm below, which is the one caller that may
# write a SECOND marker for a row and the one that never refuses.
CANDIDATES=$(awk -v pfx="roster-state/${ROSTER_VERSION}|" -v spfx="${SWEPT_SCHEMA}|" -v sid="$SID" \
                 -v mode="$MODE" -v pid="$STOP_AGENT_ID" -v atype="$STOP_AGENT_NAME" '
  index($0, spfx) == 1 {
    nf = split($0, f, "|"); a = ""; mn = ""; ms = ""
    for (i = 1; i <= nf; i++) {
      if (a  == "" && substr(f[i], 1,  9) == "agent_id=") a  = substr(f[i], 10)
      if (mn == "" && substr(f[i], 1,  5) == "name=")     mn = substr(f[i], 6)
      if (ms == "" && substr(f[i], 1,  6) == "state=")    ms = substr(f[i], 7)
    }
    if (a != "") swept[a] = 1
    # THE LATEST ANSWER, PER ROW, and latest means LAST IN THE FILE: this is an append-only
    # journal, so file order is chronological and an unconditional assignment leaves the most
    # recent marker standing. The recheck arm below reads exactly these two facts — what the
    # last answer said, and which id it was keyed by — and asks for nothing the marker does
    # not already carry.
    if (mn != "") { mstate[mn] = ms; if (a != "") magent[mn] = a }
    next
  }
  index($0, pfx) != 1 { next }
  {
    name = ""; rsession = ""; aid = ""; deliv = ""; tid = ""; fls = ""
    nf = split($0, f, "|")
    for (i = 1; i <= nf; i++) {
      if (name == ""     && substr(f[i], 1, 5)  == "name=")        name     = substr(f[i], 6)
      if (rsession == "" && substr(f[i], 1, 8)  == "session=")     rsession = substr(f[i], 9)
      if (aid == ""      && substr(f[i], 1, 9)  == "agent_id=")    aid      = substr(f[i], 10)
      if (deliv == ""    && substr(f[i], 1, 12) == "deliverable=") deliv    = substr(f[i], 13)
      if (tid == ""      && substr(f[i], 1, 12) == "teammate_id=") tid      = substr(f[i], 13)
      if (fls == ""      && substr(f[i], 1, 6)  == "files=")       fls      = substr(f[i], 7)
    }
    # The roster file is already per-session; this only fires on a hand-edited or copied
    # file, and it costs one comparison to keep the sweep honest about whose promises it is
    # answering for.
    if (rsession != "" && rsession != sid) next
    if (name == "") name = "(unnamed)"
    gsub(/\t/, " ", name)
    if (!(name in seen)) { seen[name] = 1; order[++n] = name }
    if (aid != "") agent[name] = aid
    # `teammate_id` is monotone the way `agent_id` is — the launch wall never writes it and
    # the completion arm fills it once — so the latest row that CARRIES one wins, and a row
    # appended without copying it forward cannot un-teammate a contract.
    if (tid != "") tm[name] = tid
    dl[name] = deliv
    # `files=` (S18, AC-22) is read the same way `deliverable=` is: the LATEST row value,
    # whatever it is. Post-S13 every row dispatch-preflight writes carries the key (empty
    # string for a Suites:-only brief); a pre-S13 row carries no key at all and parses to the
    # same empty value either way, so one predicate downstream (non-empty or not) covers both.
    # (No apostrophes in this paragraph: it lives inside a single-quoted awk program.)
    gsub(/\t/, " ", fls)
    fl[name] = fls
  }
  END {
    # ---------- the landing arm: ONE row, the one that just stopped ----------
    if (mode == "landing") {
      nm = ""
      # BY ID FIRST. The transcript form is filled onto the row by the recorder at
      # SubagentStart, and it is the same string this payload carries — the strongest key
      # available, and the one that survives two dispatches sharing a name.
      for (i = 1; i <= n; i++) {
        k = order[i]
        if (tm[k] == "") continue
        if ((k in agent) && agent[k] != "" && agent[k] == pid) nm = k
      }
      # BY NAME SECOND, and only over teammate rows. For a teammate `agent_type` carries the
      # dispatch name; for an async dispatch it carries the subagent type, which names no row
      # and is the join wave-03 removed for cause. The scope reads the statement the row
      # writer made about dispatch mode, never a guess at the shape of an id.
      if (nm == "" && atype != "" && (atype in seen) && tm[atype] != "") nm = atype
      # A stop we cannot place is not ours to answer for: the harness sends its own internal
      # agents through this event, and their ids are on no row of ours.
      if (nm == "") exit
      if (dl[nm] == "") exit                # declares nothing; MET vacuously either way
      a = ((nm in agent) && agent[nm] != "") ? agent[nm] : pid
      if (a == "") exit
      # Both keys, because the marker may have been written under either: the row id when the
      # identification arm ran, the payload id when it did not.
      if ((a in swept) || (pid in swept)) exit
      printf "%s\t%s\t%s\t%s\n", a, nm, "verdict", fl[nm]
      exit
    }

    # ---------- the sweep: every row the payload says has landed ----------
    for (i = 1; i <= n; i++) {
      nm = order[i]
      # TEAMMATES BELONG TO THE OTHER ARM, and this skip is load-bearing rather than tidy.
      # A teammate is keyed in `background_tasks[]` under a namespace its `agent_id` is not
      # in, and it NEVER LEAVES that array anyway (t1 §2.3) — so the moment the recorder
      # fills the row id, the landed/live predicate here reads every teammate as landed on
      # the first Stop after dispatch, 2.8 s in, and refuses a contract the agent is still
      # working on. The sweep judges what it can place; the SubagentStop arm judges the rest.
      #
      # ONE EXCEPTION, AND IT IS NOT A VERDICT (session-20260815-landing-cleanup T3, AC-5).
      # A teammate refused at SubagentStop is told so INSIDE its own sidechain, at the one
      # moment it can still act — and it does: measured live, the refused teammate read the
      # feedback and wrote the promised artifact, while the roster still said UNMET when the
      # session ended (live-verify.md B2). The refusal was right and its record was a lie
      # about the world. So a teammate row whose LATEST marker says UNMET, and whose
      # contracted deliverable the verb now finds, gets a SUPERSEDING marker appended: the
      # stream carries history plus current state, nothing is rewritten, and the block-once
      # promise is untouched because a supersession never speaks. The Stop cadence is the
      # clock; no timer is added for it.
      #
      # NEVER A FIRST VERDICT. A teammate row with no marker at all is left exactly where the
      # skip above leaves it, delivered or not — the sweep cannot tell a working teammate
      # from a finished one, and answering here is the 2.8-second false refusal this whole
      # partition exists to prevent. The recheck can only ever change an answer that the
      # SubagentStop arm already gave.
      if (tm[nm] != "") {
        if (!(nm in mstate)) continue       # unanswered: not this arm to answer
        if (mstate[nm] != "UNMET") continue # the current answer is no failure; nothing to supersede
        if (dl[nm] == "") continue          # declares nothing; MET vacuously either way
        ra = ""
        # The id off the MARKER first, and the row only as a fallback: in teammate mode a row
        # carries no `agent_id=` at all (the addressing form lives in `teammate_id=`), and the
        # marker was keyed by the transcript form off the stopping payload. Superseding under
        # a different key would leave two markers no reader could tell were about one answer.
        if ((nm in magent) && magent[nm] != "") ra = magent[nm]
        # UNREACHABLE, AND THE REASON IS NO LONGER "ONE WRITER". Two files append
        # `landing-swept/v1` lines: this one ORIGINATES them (below, off `$SWEPT_SCHEMA`),
        # and the `adopt_copy_marker` in hooks/session-poker.sh COPIES one verbatim onto the
        # successor roster when a session adopts a predecessor row — it never computes a
        # verdict, so every marker in the fleet still carries the `agent_id=` that the
        # write path below refuses to append without. That, not the writer count, is
        # what keeps `magent[nm]` populated whenever `mstate[nm]` exists.
        #
        # THE GREP THIS USED TO CITE WAS A GUARANTEED FALSE NEGATIVE: `grep -rn SWEPT_SCHEMA
        # hooks/*.sh` still returns only this file, because the poker spells the schema as a
        # literal rather than through the constant. The grep that finds both writers is
        # `grep -rn landing-swept/v1 hooks/*.sh`.
        # Kept as belt-on-belt against a future writer that COMPUTES rather than copies.
        # (No apostrophes in this paragraph: it lives inside a single-quoted awk program.)
        else if ((nm in agent) && agent[nm] != "") ra = agent[nm]
        if (ra == "") continue
        printf "%s\t%s\t%s\n", ra, nm, "recheck"
        continue
      }
      if (!(nm in agent)) continue          # never confirmed: cannot be placed
      if (dl[nm] == "") continue            # declares nothing; MET vacuously either way
      if (agent[nm] in swept) continue      # already answered for, once and for all
      printf "%s\t%s\t%s\t%s\n", agent[nm], nm, "verdict", fl[nm]
    }
  }
' "$ROSTER_FILE" 2>/dev/null)

[ -n "$CANDIDATES" ] || exit 0

LINE=""
_field() {  # <key> — by key, never by position, as every reader of these lines does
  printf '%s' "$LINE" | tr '|' '\n' | grep "^$1=" | head -1 | cut -d= -f2-
}

REFUSALS=""

# ONE DERIVATION BUDGET FOR THE WHOLE SWEEP (review-c C-17). The impact command below is
# the same call hooks/dispatch-preflight.sh makes and costs the same ~2.6-6.5 s, but it
# sits inside this per-candidate loop, and this hook is registered at "timeout": 10 on both
# Stop and SubagentStop. N offending rows would pay N x that. So the budget is spent across
# the loop rather than granted per row: whatever is left when a row asks, and nothing once
# it is gone. A row that gets no derivation still REFUSES — it names its files and says the
# suites were not derived. The one thing this must never become is a silent pass.
#
# BUILT, NOT BORROWED, for the same reason as the dispatch site: bionic's command discipline
# forbids a `timeout`/`gtimeout` binary and macOS ships neither.
LG_IMPACT_BOUND_S=6
LG_IMPACT_TICKS_LEFT=60          # 60 x 0.1s, shared by every candidate in this sweep
NOW=$(date -u +%Y-%m-%dT%H:%M:%SZ)

while IFS=$'\t' read -r AID NAME KIND CFILES; do
  [ -n "$AID" ] && [ -n "$NAME" ] || continue
  # STILL IN FLIGHT — the payload says so, and an agent that is visibly still working has
  # not failed to land. No verdict, and no marker: its one answer is still owed.
  case "$LIVE_IDS" in *"|$AID|"*) continue ;; esac

  # Run from the repo, because the sweeper resolves its own state directory from the working
  # directory, and with the payload's session key. `|| exit 9` keeps a failed `cd` out of the
  # exit-1 band: exit 1 is the verb's "at least one UNMET row", and nothing else may be
  # allowed to spell it.
  VERDICT=$( cd "$REPO" 2>/dev/null || exit 9
             CLAUDE_CODE_SESSION_ID="$SID" bash "$SWEEPER" verdict "$NAME" 2>/dev/null )
  VERDICT_RC=$?

  # AN ANSWER WE DID NOT GET IS NOT AN ANSWER. Exit 2 is a refusal (the verb was redirected
  # away from the roster and says so), 3 is no session key, anything else is an error — and
  # none of them may mark a row closed, because the row has not been judged.
  case "$VERDICT_RC" in 0|1) : ;; *) continue ;; esac

  # THE LINE THE SCOPED VERB RETURNED, and no second lookup by name. `verdict <name>`
  # answers for that name alone and folds the roster to one row per name, so its output
  # carries at most one machine line and taking the first IS taking this contract's.
  LINE=$(printf '%s\n' "$VERDICT" | grep -F 'landing-verdict/v1|' | head -1)
  [ -n "$LINE" ] || continue

  STATE=$(_field state)

  # A RECHECK SPENDS A MARKER ONLY ON A CHANGED ANSWER. The row already has one saying UNMET;
  # a second saying the same thing records nothing and would be appended on every turn end
  # for the rest of the session — the marker-spam shape. Only MET supersedes: STILL-LIVE,
  # WAIVED and AMBIGUOUS are not the recovery this arm exists to record, and UNMET is the
  # answer already standing.
  if [ "$KIND" = "recheck" ] && [ "$STATE" != "MET" ]; then
    continue
  fi

  # APPENDED HERE, PER ROW, THE MOMENT ITS VERDICT IS DECIDED — not accumulated across the
  # whole loop and written once at the end (t6-review.md F-2, measured: a sweep killed 5s
  # into a 200-candidate run, ~60 already verdicted, banked ZERO marks under the old single
  # trailing append). This is the same lock-free discipline the trailing append relied on —
  # one line, well under a pipe buffer, O_APPEND — just paid once per row instead of once
  # per sweep, so a sweep killed mid-loop still banks every verdict already decided.
  #
  # THE ONE WRITER (S15, AC-26): `swept_marker_write`, defined above, owns this printf;
  # hooks/session-poker.sh's `adopt_copy_marker` never re-spells it.
  swept_marker_write "$ROSTER_FILE" "$NOW" "$SID" "$NAME" "$AID" "$STATE"

  # AND A SUPERSESSION NEVER SPEAKS. Its marker is MET by construction, so nothing below
  # would fire anyway — but the reason it must not is stronger than the arithmetic: the row
  # has already been refused once, the agent has already acted on that refusal, and the whole
  # promise of this gate is that it blocks once. Recording the recovery is the entire job.
  [ "$KIND" = "recheck" ] && continue

  # ---------------------------------------------------------- Files: RECONCILIATION (S18, AC-22)
  #
  # INDEPENDENT OF THE DELIVERABLE VERDICT ABOVE, and run exactly once — this row reaches
  # this line only as a first-time "verdict" candidate (recheck already continued above,
  # and a row with no `deliverable=` never became a candidate at all — see the awk END
  # block's own "declares nothing" skips, which this check inherits rather than re-states).
  if [ -n "$CFILES" ]; then
    LG_WT=$(_lg_worktree_for_name "$REPO" "$NAME")
    if [ -n "$LG_WT" ] && [ -d "$LG_WT" ]; then
      # THE BASE IS THE MERGE-BASE WITH THE MAIN CHECKOUT'S CURRENT BRANCH, recomputed here
      # rather than read off a stored value: no roster field records the sha a worktree
      # spawned from, and `worktree.sh`'s own `land` verb does not need one either — it
      # counts commits `HEAD..branch` from the main checkout. A merge-base is exactly
      # "everything this branch has added since it diverged", which is what a `Files:`
      # declaration is a promise ABOUT, and recomputing it survives the ordinary case where
      # the main branch has moved on since the tree was spawned — a stored base sha would not.
      LG_MAIN_BRANCH=$(git -C "$REPO" rev-parse --abbrev-ref HEAD 2>/dev/null)
      LG_BASE=""
      # A DETACHED MAIN CHECKOUT IS NOT A BRANCH NAME (review-a A-5). `rev-parse
      # --abbrev-ref HEAD` prints the literal string `HEAD` there, and `HEAD` resolves
      # INSIDE the worktree to the worktree's own tip — so the merge-base comes back
      # non-empty, the diff comes back EMPTY, and every landing reconciles clean with no
      # refusal and no diagnostic. `git bisect`, `git checkout <tag>` and a checkout parked
      # on a sha are all ordinary states for this repository during an integration.
      case "$LG_MAIN_BRANCH" in HEAD) LG_MAIN_BRANCH="" ;; esac
      [ -n "$LG_MAIN_BRANCH" ] && LG_BASE=$(git -C "$LG_WT" merge-base "$LG_MAIN_BRANCH" HEAD 2>/dev/null)
      if [ -z "$LG_BASE" ]; then
        # ANNOUNCED INERT, the standard tests/run.sh:267-272 sets for the adoption wall:
        # "a wall that is off and quiet is indistinguishable from a wall that is passing
        # everything". Unrelated histories, a worktree with no commits and any other
        # merge-base failure land here too, and each says so rather than passing silently.
        if [ -z "$LG_MAIN_BRANCH" ]; then
          LG_WHY="the main checkout is on no branch (detached HEAD), so there is no branch to take a merge-base from"
        else
          LG_WHY="no merge-base between ${LG_MAIN_BRANCH} and this tree"
        fi
        echo "landing-gate: ${LG_WHY} — the Files: reconciliation is INERT for row ${NAME}; its diff was NOT checked against '${CFILES}'" >&2
      fi
      if [ -n "$LG_BASE" ]; then
        LG_OUTSIDE=""
        while IFS= read -r LG_DF; do
          [ -n "$LG_DF" ] || continue
          _lg_path_declared "$LG_DF" "$CFILES" && continue
          LG_OUTSIDE="${LG_OUTSIDE}${LG_OUTSIDE:+ }${LG_DF}"
        done <<LGDIFF
$(git -C "$LG_WT" diff --name-only "${LG_BASE}..HEAD" 2>/dev/null)
LGDIFF
        if [ -n "$LG_OUTSIDE" ]; then
          # THE SAME COMMAND, THE SAME CONFIG KEY hooks/dispatch-preflight.sh reads (S13),
          # re-asked of the offending files alone (spec AC-22: "naming the files and the
          # suites they imply"). Absent command -> name the files only, exactly as the
          # dispatch wall itself falls back when nothing is configured.
          LG_IMPACT_CMD=$(config_value "$REPO" "impact-command" "")
          LG_SUITES=""
          LG_SUITES_NOTE=""
          if [ -n "$LG_IMPACT_CMD" ]; then
            if [ "$LG_IMPACT_TICKS_LEFT" -le 0 ]; then
              LG_SUITES_NOTE=" (this sweep's ${LG_IMPACT_BOUND_S}s derivation budget was spent on earlier rows, so the suites these files imply are NOT named here — derive them by hand)"
            else
              LG_IMPACT_TMP="${TMPDIR:-/tmp}/bionic-lg-impact-$$-${RANDOM}.out"
              # `set -f` AROUND THE SPLIT (review-a A-11). `$LG_OUTSIDE` is built from `git
              # diff --name-only`, and a committed path carrying `*`, `?` or `[` would
              # otherwise be pathname-expanded against $REPO and hand the command files
              # that were never in the diff. The dispatch site guards the identical
              # construction; this one did not.
              set -f
              # shellcheck disable=SC2086  # the COMMAND is configuration and is meant to split
              ( cd "$REPO" 2>/dev/null && $LG_IMPACT_CMD $LG_OUTSIDE >"$LG_IMPACT_TMP" 2>/dev/null ) &
              LG_IMPACT_PID=$!
              set +f
              LG_TICKS=0
              LG_OVERRAN=0
              while kill -0 "$LG_IMPACT_PID" 2>/dev/null; do
                if [ "$LG_TICKS" -ge "$LG_IMPACT_TICKS_LEFT" ]; then
                  kill -TERM "$LG_IMPACT_PID" 2>/dev/null
                  LG_OVERRAN=1
                  break
                fi
                sleep 0.1
                LG_TICKS=$((LG_TICKS + 1))
              done
              wait "$LG_IMPACT_PID" 2>/dev/null
              LG_IMPACT_TICKS_LEFT=$((LG_IMPACT_TICKS_LEFT - LG_TICKS))
              if [ "$LG_OVERRAN" -eq 1 ]; then
                LG_SUITES_NOTE=" (the impact command did not answer within this sweep's ${LG_IMPACT_BOUND_S}s derivation budget, so the suites these files imply are NOT named here — derive them by hand)"
              else
                LG_SUITES=$(awk -F'\t' '$1 != "" { print $1 }' "$LG_IMPACT_TMP" 2>/dev/null | sort -u | tr '\n' ' ')
                LG_SUITES="${LG_SUITES% }"
              fi
              rm -f "$LG_IMPACT_TMP"
            fi
          fi
          REFUSALS="${REFUSALS}LANDING DIFF OUTSIDE Files: — ${NAME} touched: ${LG_OUTSIDE}${LG_SUITES:+ (suites: ${LG_SUITES})}${LG_SUITES_NOTE} — not declared. Add the file(s) to Files: and re-derive, or revert them before landing.
"
        fi
      fi
    fi
  fi
  # A Suites:-only brief (AC-20's other half), or a pre-S13 row, declared no Files: at all,
  # so there is no declared set to reconcile the diff against. SILENT, on the same footing
  # as every other "cannot judge this" path in this file: this is the ordinary case for most
  # of the fleet today (Files: is the newer of AC-20's two labels), and a stderr line on
  # every such landing would turn the common case into noise on every turn end — the exact
  # false-alarm shape the rest of this gate exists to end. The disposition is documented
  # once, above, in the FAIL DIRECTIONS table; it is not re-announced per row.

  [ "$VERDICT_RC" -eq 1 ] || continue
  [ "$STATE" = "UNMET" ] || continue

  # AN ACKED ROW IS CLOSED FOR EVERY READER (epic-16 wave-02 slice S3, R2). The orchestrator
  # verified this agent's completion and made that durable; reporting it again over artifacts
  # a human has already accounted for is the false alarm this wave exists to end. Read off
  # the verdict line, which is where the one reader of that ledger publishes it (S9).
  [ "$(_field acked)" = "yes" ] && continue

  # The refusal is the verb's own detail, unedited, prefixed by the row it is about. It names
  # every failing conjunct — `missing=`, `empty=`, `stale=` with both stamps — because a
  # reader told only "unmet" has nothing to act on. The ROW NAME is what the sweep adds and
  # the per-agent gate did not need: a sweep answers about contracts rather than about
  # whoever is stopping, so without it the reader cannot tell which dispatch to chase.
  REFUSALS="${REFUSALS}LANDING CONTRACT UNMET — ${NAME}: $(_field detail). Land the contract (write the named artifacts), or stop again to pass — this gate blocks once.
"
done <<EOF
$CANDIDATES
EOF

[ -n "$REFUSALS" ] || exit 0
printf '%s' "$REFUSALS" >&2
exit 2
